linters:
  enable:
    - exhaustive
    - goconst
    #- godox
    - gofmt
    - lll
    - mnd
    - misspell
linters-settings:
  lll:
    line-length: 100
    tab-width: 4
  mnd:
    ignored-functions:
      - "^make"
