version: "2"
linters:
  enable:
    - exhaustive
    - goconst
    - lll
    - misspell
    - mnd
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - copyloopvar
    - gosec
    - nolintlint
    - prealloc
#    - depguard
  settings:
    lll:
      line-length: 140
      tab-width: 4
    mnd:
      ignored-functions:
        - ^make
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
