// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

// Package trace provides TLA+ trace validation for the hybrid event system.
//
// It records execution traces as sequences of TLA+ states and generates
// a Trace.tla module that can be validated against the HybridEvents
// specification using TLC.
//
// Usage:
//  1. Create a Recorder with NewRecorder(maxItems, workers, syncInterval).
//  2. Record states via rec.Record(Snapshot(...)) after each action.
//  3. Call rec.WriteTLA(path) to generate the Trace.tla module.
//  4. Run TLC: java -jar tla2tools.jar -config TraceHybridEvents.cfg -deadlock TraceHybridEvents.tla
package trace //nolint:revive

import (
	"fmt"
	"maps"
	"os"
	"slices"
	"strings"
)

const (
	tlaEmptyFunc = "<<>>" // TLA+ representation of an empty function
	filePerms    = 0644
)

// State represents the value of all TLA+ variables after one action.
// Each field maps 1:1 to a variable in HybridEvents.tla.
type State struct {
	Action       string            // which TLA+ action produced this state
	DB           map[int]string    // item -> "ABSENT"|"PENDING"|"DONE"
	EventChannel map[int]bool      // set of item IDs with pending notifications
	WorkerState  map[string]string // worker -> "idle"|"processing"|"dead"
	WorkerClock  map[string]int    // worker -> steps since last sync
	Processed    map[int]bool      // set of items that have been processed
	ProducerNext int               // next item ID to produce (1-based)
}

// Recorder records a sequence of TLA+ states for trace validation.
type Recorder struct {
	States       []State
	MaxItems     int
	Workers      []string
	SyncInterval int
}

// NewRecorder creates a trace recorder for a model with the given parameters.
func NewRecorder(maxItems int, workers []string, syncInterval int) *Recorder {
	sorted := make([]string, len(workers))
	copy(sorted, workers)
	slices.Sort(sorted)
	return &Recorder{
		MaxItems:     maxItems,
		Workers:      sorted,
		SyncInterval: syncInterval,
	}
}

// Record appends a state to the trace.
func (r *Recorder) Record(s State) {
	r.States = append(r.States, s)
}

// Snapshot creates a deep copy of the current TLA+ state.
func Snapshot(
	action string,
	db map[int]string,
	ec map[int]bool,
	ws map[string]string,
	wc map[string]int,
	proc map[int]bool,
	producerNext int,
) State {
	dbCopy := make(map[int]string, len(db))
	maps.Copy(dbCopy, db)
	ecCopy := make(map[int]bool, len(ec))
	maps.Copy(ecCopy, ec)
	wsCopy := make(map[string]string, len(ws))
	maps.Copy(wsCopy, ws)
	wcCopy := make(map[string]int, len(wc))
	maps.Copy(wcCopy, wc)
	procCopy := make(map[int]bool, len(proc))
	maps.Copy(procCopy, proc)

	return State{
		Action:       action,
		DB:           dbCopy,
		EventChannel: ecCopy,
		WorkerState:  wsCopy,
		WorkerClock:  wcCopy,
		Processed:    procCopy,
		ProducerNext: producerNext,
	}
}

// WriteTLA writes the trace as a TLA+ module to the given path.
// The generated module defines a `trace` operator as a sequence of records
// using the TLC module's :> and @@ operators for function construction.
func (r *Recorder) WriteTLA(path string) (string, error) {
	content := r.FormatTLA()
	return content, os.WriteFile(path, []byte(content), filePerms)
}

// FormatTLA returns the TLA+ module content as a string.
func (r *Recorder) FormatTLA() string {
	var b strings.Builder
	b.WriteString(
		"---------------------------- MODULE Trace ----------------------------\n")
	b.WriteString("(* Auto-generated by Go trace validation test. DO NOT EDIT. *)\n\n")
	b.WriteString("EXTENDS Integers, TLC\n\n")

	b.WriteString("trace == <<\n")
	for i, s := range r.States {
		b.WriteString("  [ ")
		fmt.Fprintf(&b, "action |-> %q,\n", s.Action)
		fmt.Fprintf(&b, "    db |-> %s,\n", formatIntKeyedFunc(s.DB))
		fmt.Fprintf(&b, "    eventChannel |-> %s,\n", formatIntSet(s.EventChannel))
		fmt.Fprintf(&b, "    workerState |-> %s,\n", formatStrKeyedFunc(s.WorkerState))
		fmt.Fprintf(&b, "    workerClock |-> %s,\n", formatStrKeyedIntFunc(s.WorkerClock))
		fmt.Fprintf(&b, "    processed |-> %s,\n", formatIntSet(s.Processed))
		fmt.Fprintf(&b, "    producerNext |-> %d ]", s.ProducerNext)
		if i < len(r.States)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(">>\n\n")
	b.WriteString(
		"==========================================================================\n")
	return b.String()
}

// formatIntKeyedFunc formats map[int]string as a TLA+ function: (1 :> "A" @@ 2 :> "B").
func formatIntKeyedFunc(m map[int]string) string {
	keys := sortedIntKeys(m)
	if len(keys) == 0 {
		return tlaEmptyFunc
	}
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = fmt.Sprintf("%d :> %q", k, m[k])
	}
	return "(" + strings.Join(parts, " @@ ") + ")"
}

// formatStrKeyedFunc formats map[string]string as a TLA+ function.
func formatStrKeyedFunc(m map[string]string) string {
	keys := sortedStrKeys(m)
	if len(keys) == 0 {
		return tlaEmptyFunc
	}
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = fmt.Sprintf("%q :> %q", k, m[k])
	}
	return "(" + strings.Join(parts, " @@ ") + ")"
}

// formatStrKeyedIntFunc formats map[string]int as a TLA+ function.
func formatStrKeyedIntFunc(m map[string]int) string {
	keys := sortedStrKeysInt(m)
	if len(keys) == 0 {
		return tlaEmptyFunc
	}
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = fmt.Sprintf("%q :> %d", k, m[k])
	}
	return "(" + strings.Join(parts, " @@ ") + ")"
}

// formatIntSet formats map[int]bool as a TLA+ set: {1, 2, 3}.
func formatIntSet(m map[int]bool) string {
	keys := make([]int, 0, len(m))
	for k, v := range m {
		if v {
			keys = append(keys, k)
		}
	}
	if len(keys) == 0 {
		return "{}"
	}
	slices.Sort(keys)
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = fmt.Sprintf("%d", k)
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func sortedIntKeys[V any](m map[int]V) []int {
	keys := make([]int, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

func sortedStrKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

func sortedStrKeysInt(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}
