[package]
name = "http-health-check"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["macros", "time", "rt-multi-thread"] }
tracing.workspace = true
