<!--
File generated by internal/config/generate.
DO NOT EDIT.
-->

<!-- markdownlint-disable line_length -->
# Node Configuration

The node is configurable through environment variables.
(There is no other way to configure it.)

This file documents the configuration options.

<!-- markdownlint-disable MD012 -->
{{- range .}}

## {{backtick .Name}}

{{.Description}}

* **Type:** {{backtick .GoType}}
{{- if .Default}}
* **Default:** {{.Default | quote | backtick}}
{{- end}}
{{- end}}