// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

package trace //nolint:revive

import (
	"fmt"
	"os"
	"slices"
	"strings"
)

const (
	tlaEmptyFunc = "<<>>"
	filePerms    = 0644
)

// Recorder records a sequence of DrainProtocol states.
type Recorder struct {
	States []State
}

// NewRecorder creates a new trace recorder.
func NewRecorder() *Recorder {
	return &Recorder{}
}

// Record appends a state to the trace.
func (r *Recorder) Record(s State) {
	r.States = append(r.States, s)
}

// WriteTLA writes the trace as a TLA+ module to the given path.
func (r *Recorder) WriteTLA(path string) (string, error) {
	content := r.FormatTLA()
	return content, os.WriteFile(path, []byte(content), filePerms)
}

// FormatTLA returns the TLA+ module content.
func (r *Recorder) FormatTLA() string {
	var b strings.Builder
	b.WriteString(
		"---------------------------- MODULE Trace ----------------------------\n")
	b.WriteString("(* Auto-generated by Go drain trace validation test. DO NOT EDIT. *)\n\n")
	b.WriteString("EXTENDS Integers, TLC\n\n")
	b.WriteString("trace == <<\n")
	for i, s := range r.States {
		b.WriteString("  [ ")
		fmt.Fprintf(&b, "action |-> %q,\n", s.Action)
		fmt.Fprintf(&b, "    dbEnabled |-> %s,\n", formatIntBoolFunc(s.DBEnabled))
		fmt.Fprintf(&b, "    dbDeleted |-> %s,\n", formatIntBoolFunc(s.DBDeleted))
		fmt.Fprintf(&b, "    dbAcks |-> %s,\n", formatAckFunc(s.DBAcks))
		fmt.Fprintf(&b, "    dbHardDeleted |-> %s,\n", formatIntSet(s.DBHardDeleted))
		fmt.Fprintf(&b, "    forceDeleted |-> %s,\n", formatIntSet(s.ForceDeleted))
		fmt.Fprintf(&b, "    advMachines |-> %s,\n", formatIntSet(s.AdvMachines))
		fmt.Fprintf(&b, "    clmKnown |-> %s,\n", formatIntSet(s.ClmKnown))
		fmt.Fprintf(&b, "    clmInFlight |-> %s,\n", formatIntSet(s.ClmInFlight))
		fmt.Fprintf(&b, "    prtKnown |-> %s,\n", formatIntSet(s.PrtKnown))
		fmt.Fprintf(&b, "    prtInFlight |-> %s,\n", formatIntSet(s.PrtInFlight))
		fmt.Fprintf(&b, "    svcAlive |-> %s ]", formatStrBoolFunc(s.SvcAlive))
		if i < len(r.States)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(">>\n\n")
	b.WriteString(
		"==========================================================================\n")
	return b.String()
}

func formatIntBoolFunc(m map[int]bool) string {
	keys := sortedIntKeys(m)
	if len(keys) == 0 {
		return tlaEmptyFunc
	}
	parts := make([]string, len(keys))
	for i, key := range keys {
		parts[i] = fmt.Sprintf("%d :> %s", key, tlaBool(m[key]))
	}
	return "(" + strings.Join(parts, " @@ ") + ")"
}

func formatStrBoolFunc(m map[string]bool) string {
	keys := sortedStrKeys(m)
	if len(keys) == 0 {
		return tlaEmptyFunc
	}
	parts := make([]string, len(keys))
	for i, key := range keys {
		parts[i] = fmt.Sprintf("%q :> %s", key, tlaBool(m[key]))
	}
	return "(" + strings.Join(parts, " @@ ") + ")"
}

func formatAckFunc(m map[int]map[string]bool) string {
	keys := sortedIntKeysNested(m)
	if len(keys) == 0 {
		return tlaEmptyFunc
	}
	parts := make([]string, len(keys))
	for i, key := range keys {
		parts[i] = fmt.Sprintf("%d :> %s", key, formatStrSet(m[key]))
	}
	return "(" + strings.Join(parts, " @@ ") + ")"
}

func formatIntSet(m map[int]bool) string {
	keys := make([]int, 0, len(m))
	for key, value := range m {
		if value {
			keys = append(keys, key)
		}
	}
	if len(keys) == 0 {
		return "{}"
	}
	slices.Sort(keys)
	parts := make([]string, len(keys))
	for i, key := range keys {
		parts[i] = fmt.Sprintf("%d", key)
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func formatStrSet(m map[string]bool) string {
	keys := make([]string, 0, len(m))
	for key, value := range m {
		if value {
			keys = append(keys, key)
		}
	}
	if len(keys) == 0 {
		return "{}"
	}
	slices.Sort(keys)
	parts := make([]string, len(keys))
	for i, key := range keys {
		parts[i] = fmt.Sprintf("%q", key)
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func sortedIntKeys[V any](m map[int]V) []int {
	keys := make([]int, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}

func sortedIntKeysNested(m map[int]map[string]bool) []int {
	keys := make([]int, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}

func sortedStrKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}

func tlaBool(value bool) string {
	if value {
		return "TRUE"
	}
	return "FALSE"
}
