//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ApplicationHealth = &struct {
	Running    postgres.StringExpression
	Stopped    postgres.StringExpression
	Failed     postgres.StringExpression
	Inoperable postgres.StringExpression
}{
	Running:    postgres.NewEnumValue("RUNNING"),
	Stopped:    postgres.NewEnumValue("STOPPED"),
	Failed:     postgres.NewEnumValue("FAILED"),
	Inoperable: postgres.NewEnumValue("INOPERABLE"),
}
