//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var BondEventType = &struct {
	PartialBondRefund postgres.StringExpression
	BondRecovered     postgres.StringExpression
}{
	PartialBondRefund: postgres.NewEnumValue("PARTIAL_BOND_REFUND"),
	BondRecovered:     postgres.NewEnumValue("BOND_RECOVERED"),
}
