//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var BondDisposition = &struct {
	TournamentRunning postgres.StringExpression
	NoWinner          postgres.StringExpression
	Recoverable       postgres.StringExpression
	Recovered         postgres.StringExpression
}{
	TournamentRunning: postgres.NewEnumValue("TOURNAMENT_RUNNING"),
	NoWinner:          postgres.NewEnumValue("NO_WINNER"),
	Recoverable:       postgres.NewEnumValue("RECOVERABLE"),
	Recovered:         postgres.NewEnumValue("RECOVERED"),
}
