//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var DefaultBlock = &struct {
	Finalized postgres.StringExpression
	Latest    postgres.StringExpression
	Pending   postgres.StringExpression
	Safe      postgres.StringExpression
}{
	Finalized: postgres.NewEnumValue("FINALIZED"),
	Latest:    postgres.NewEnumValue("LATEST"),
	Pending:   postgres.NewEnumValue("PENDING"),
	Safe:      postgres.NewEnumValue("SAFE"),
}
