//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var EpochStatus = &struct {
	Open            postgres.StringExpression
	Closed          postgres.StringExpression
	InputsProcessed postgres.StringExpression
	ClaimComputed   postgres.StringExpression
	ClaimSubmitted  postgres.StringExpression
	ClaimAccepted   postgres.StringExpression
	ClaimRejected   postgres.StringExpression
}{
	Open:            postgres.NewEnumValue("OPEN"),
	Closed:          postgres.NewEnumValue("CLOSED"),
	InputsProcessed: postgres.NewEnumValue("INPUTS_PROCESSED"),
	ClaimComputed:   postgres.NewEnumValue("CLAIM_COMPUTED"),
	ClaimSubmitted:  postgres.NewEnumValue("CLAIM_SUBMITTED"),
	ClaimAccepted:   postgres.NewEnumValue("CLAIM_ACCEPTED"),
	ClaimRejected:   postgres.NewEnumValue("CLAIM_REJECTED"),
}
