//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var InnerTournamentDisposition = &struct {
	Unsettled  postgres.StringExpression
	Winner     postgres.StringExpression
	Eliminable postgres.StringExpression
}{
	Unsettled:  postgres.NewEnumValue("UNSETTLED"),
	Winner:     postgres.NewEnumValue("WINNER"),
	Eliminable: postgres.NewEnumValue("ELIMINABLE"),
}
