//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var MatchPhase = &struct {
	Uninitialized postgres.StringExpression
	Bisecting     postgres.StringExpression
	ReadyToSeal   postgres.StringExpression
	Sealed        postgres.StringExpression
}{
	Uninitialized: postgres.NewEnumValue("UNINITIALIZED"),
	Bisecting:     postgres.NewEnumValue("BISECTING"),
	ReadyToSeal:   postgres.NewEnumValue("READY_TO_SEAL"),
	Sealed:        postgres.NewEnumValue("SEALED"),
}
