//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var MatchDeletionReason = &struct {
	Step            postgres.StringExpression
	Timeout         postgres.StringExpression
	ChildTournament postgres.StringExpression
	NotDeleted      postgres.StringExpression
}{
	Step:            postgres.NewEnumValue("STEP"),
	Timeout:         postgres.NewEnumValue("TIMEOUT"),
	ChildTournament: postgres.NewEnumValue("CHILD_TOURNAMENT"),
	NotDeleted:      postgres.NewEnumValue("NOT_DELETED"),
}
