//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var MatchTimeoutOutcome = &struct {
	None          postgres.StringExpression
	OneWins       postgres.StringExpression
	TwoWins       postgres.StringExpression
	EliminateBoth postgres.StringExpression
}{
	None:          postgres.NewEnumValue("NONE"),
	OneWins:       postgres.NewEnumValue("ONE_WINS"),
	TwoWins:       postgres.NewEnumValue("TWO_WINS"),
	EliminateBoth: postgres.NewEnumValue("ELIMINATE_BOTH"),
}
