//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TournamentStandingState = &struct {
	MatchesActive                postgres.StringExpression
	AwaitingClosure              postgres.StringExpression
	RootWinner                   postgres.StringExpression
	RootFailed                   postgres.StringExpression
	InnerWinner                  postgres.StringExpression
	InnerEliminableNoWinner      postgres.StringExpression
	InnerEliminableWinnerExpired postgres.StringExpression
}{
	MatchesActive:                postgres.NewEnumValue("MATCHES_ACTIVE"),
	AwaitingClosure:              postgres.NewEnumValue("AWAITING_CLOSURE"),
	RootWinner:                   postgres.NewEnumValue("ROOT_WINNER"),
	RootFailed:                   postgres.NewEnumValue("ROOT_FAILED"),
	InnerWinner:                  postgres.NewEnumValue("INNER_WINNER"),
	InnerEliminableNoWinner:      postgres.NewEnumValue("INNER_ELIMINABLE_NO_WINNER"),
	InnerEliminableWinnerExpired: postgres.NewEnumValue("INNER_ELIMINABLE_WINNER_EXPIRED"),
}
