//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var WinnerCommitment = &struct {
	None postgres.StringExpression
	One  postgres.StringExpression
	Two  postgres.StringExpression
}{
	None: postgres.NewEnumValue("NONE"),
	One:  postgres.NewEnumValue("ONE"),
	Two:  postgres.NewEnumValue("TWO"),
}
