//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ApplicationServiceAck = newApplicationServiceAckTable("public", "application_service_ack", "")

type applicationServiceAckTable struct {
	postgres.Table

	// Columns
	ApplicationID postgres.ColumnInteger
	ServiceName   postgres.ColumnString
	AckedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ApplicationServiceAckTable struct {
	applicationServiceAckTable

	EXCLUDED applicationServiceAckTable
}

// AS creates new ApplicationServiceAckTable with assigned alias
func (a ApplicationServiceAckTable) AS(alias string) *ApplicationServiceAckTable {
	return newApplicationServiceAckTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ApplicationServiceAckTable with assigned schema name
func (a ApplicationServiceAckTable) FromSchema(schemaName string) *ApplicationServiceAckTable {
	return newApplicationServiceAckTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ApplicationServiceAckTable with assigned table prefix
func (a ApplicationServiceAckTable) WithPrefix(prefix string) *ApplicationServiceAckTable {
	return newApplicationServiceAckTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ApplicationServiceAckTable with assigned table suffix
func (a ApplicationServiceAckTable) WithSuffix(suffix string) *ApplicationServiceAckTable {
	return newApplicationServiceAckTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newApplicationServiceAckTable(schemaName, tableName, alias string) *ApplicationServiceAckTable {
	return &ApplicationServiceAckTable{
		applicationServiceAckTable: newApplicationServiceAckTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newApplicationServiceAckTableImpl("", "excluded", ""),
	}
}

func newApplicationServiceAckTableImpl(schemaName, tableName, alias string) applicationServiceAckTable {
	var (
		ApplicationIDColumn = postgres.IntegerColumn("application_id")
		ServiceNameColumn   = postgres.StringColumn("service_name")
		AckedAtColumn       = postgres.TimestampzColumn("acked_at")
		allColumns          = postgres.ColumnList{ApplicationIDColumn, ServiceNameColumn, AckedAtColumn}
		mutableColumns      = postgres.ColumnList{AckedAtColumn}
		defaultColumns      = postgres.ColumnList{AckedAtColumn}
	)

	return applicationServiceAckTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID: ApplicationIDColumn,
		ServiceName:   ServiceNameColumn,
		AckedAt:       AckedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
