//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BondEvents = newBondEventsTable("public", "bond_events", "")

type bondEventsTable struct {
	postgres.Table

	// Columns
	ApplicationID     postgres.ColumnInteger
	EpochIndex        postgres.ColumnFloat
	TournamentAddress postgres.ColumnBytea
	Type              postgres.ColumnString
	BlockNumber       postgres.ColumnFloat
	TxHash            postgres.ColumnBytea
	LogIndex          postgres.ColumnFloat
	Recipient         postgres.ColumnBytea
	Value             postgres.ColumnFloat
	Success           postgres.ColumnBool
	Commitment        postgres.ColumnBytea
	Claimer           postgres.ColumnBytea
	Payment           postgres.ColumnFloat
	Burned            postgres.ColumnFloat
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BondEventsTable struct {
	bondEventsTable

	EXCLUDED bondEventsTable
}

// AS creates new BondEventsTable with assigned alias
func (a BondEventsTable) AS(alias string) *BondEventsTable {
	return newBondEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BondEventsTable with assigned schema name
func (a BondEventsTable) FromSchema(schemaName string) *BondEventsTable {
	return newBondEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BondEventsTable with assigned table prefix
func (a BondEventsTable) WithPrefix(prefix string) *BondEventsTable {
	return newBondEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BondEventsTable with assigned table suffix
func (a BondEventsTable) WithSuffix(suffix string) *BondEventsTable {
	return newBondEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBondEventsTable(schemaName, tableName, alias string) *BondEventsTable {
	return &BondEventsTable{
		bondEventsTable: newBondEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newBondEventsTableImpl("", "excluded", ""),
	}
}

func newBondEventsTableImpl(schemaName, tableName, alias string) bondEventsTable {
	var (
		ApplicationIDColumn     = postgres.IntegerColumn("application_id")
		EpochIndexColumn        = postgres.FloatColumn("epoch_index")
		TournamentAddressColumn = postgres.ByteaColumn("tournament_address")
		TypeColumn              = postgres.StringColumn("type")
		BlockNumberColumn       = postgres.FloatColumn("block_number")
		TxHashColumn            = postgres.ByteaColumn("tx_hash")
		LogIndexColumn          = postgres.FloatColumn("log_index")
		RecipientColumn         = postgres.ByteaColumn("recipient")
		ValueColumn             = postgres.FloatColumn("value")
		SuccessColumn           = postgres.BoolColumn("success")
		CommitmentColumn        = postgres.ByteaColumn("commitment")
		ClaimerColumn           = postgres.ByteaColumn("claimer")
		PaymentColumn           = postgres.FloatColumn("payment")
		BurnedColumn            = postgres.FloatColumn("burned")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		allColumns              = postgres.ColumnList{ApplicationIDColumn, EpochIndexColumn, TournamentAddressColumn, TypeColumn, BlockNumberColumn, TxHashColumn, LogIndexColumn, RecipientColumn, ValueColumn, SuccessColumn, CommitmentColumn, ClaimerColumn, PaymentColumn, BurnedColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{EpochIndexColumn, TournamentAddressColumn, TypeColumn, BlockNumberColumn, RecipientColumn, ValueColumn, SuccessColumn, CommitmentColumn, ClaimerColumn, PaymentColumn, BurnedColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return bondEventsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID:     ApplicationIDColumn,
		EpochIndex:        EpochIndexColumn,
		TournamentAddress: TournamentAddressColumn,
		Type:              TypeColumn,
		BlockNumber:       BlockNumberColumn,
		TxHash:            TxHashColumn,
		LogIndex:          LogIndexColumn,
		Recipient:         RecipientColumn,
		Value:             ValueColumn,
		Success:           SuccessColumn,
		Commitment:        CommitmentColumn,
		Claimer:           ClaimerColumn,
		Payment:           PaymentColumn,
		Burned:            BurnedColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
