//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Commitments = newCommitmentsTable("public", "commitments", "")

type commitmentsTable struct {
	postgres.Table

	// Columns
	ApplicationID     postgres.ColumnInteger
	EpochIndex        postgres.ColumnFloat
	TournamentAddress postgres.ColumnString
	Commitment        postgres.ColumnString
	FinalStateHash    postgres.ColumnString
	SubmitterAddress  postgres.ColumnString
	BlockNumber       postgres.ColumnFloat
	TxHash            postgres.ColumnString
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CommitmentsTable struct {
	commitmentsTable

	EXCLUDED commitmentsTable
}

// AS creates new CommitmentsTable with assigned alias
func (a CommitmentsTable) AS(alias string) *CommitmentsTable {
	return newCommitmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CommitmentsTable with assigned schema name
func (a CommitmentsTable) FromSchema(schemaName string) *CommitmentsTable {
	return newCommitmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CommitmentsTable with assigned table prefix
func (a CommitmentsTable) WithPrefix(prefix string) *CommitmentsTable {
	return newCommitmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CommitmentsTable with assigned table suffix
func (a CommitmentsTable) WithSuffix(suffix string) *CommitmentsTable {
	return newCommitmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCommitmentsTable(schemaName, tableName, alias string) *CommitmentsTable {
	return &CommitmentsTable{
		commitmentsTable: newCommitmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCommitmentsTableImpl("", "excluded", ""),
	}
}

func newCommitmentsTableImpl(schemaName, tableName, alias string) commitmentsTable {
	var (
		ApplicationIDColumn     = postgres.IntegerColumn("application_id")
		EpochIndexColumn        = postgres.FloatColumn("epoch_index")
		TournamentAddressColumn = postgres.StringColumn("tournament_address")
		CommitmentColumn        = postgres.StringColumn("commitment")
		FinalStateHashColumn    = postgres.StringColumn("final_state_hash")
		SubmitterAddressColumn  = postgres.StringColumn("submitter_address")
		BlockNumberColumn       = postgres.FloatColumn("block_number")
		TxHashColumn            = postgres.StringColumn("tx_hash")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		allColumns              = postgres.ColumnList{ApplicationIDColumn, EpochIndexColumn, TournamentAddressColumn, CommitmentColumn, FinalStateHashColumn, SubmitterAddressColumn, BlockNumberColumn, TxHashColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{FinalStateHashColumn, SubmitterAddressColumn, BlockNumberColumn, TxHashColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return commitmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID:     ApplicationIDColumn,
		EpochIndex:        EpochIndexColumn,
		TournamentAddress: TournamentAddressColumn,
		Commitment:        CommitmentColumn,
		FinalStateHash:    FinalStateHashColumn,
		SubmitterAddress:  SubmitterAddressColumn,
		BlockNumber:       BlockNumberColumn,
		TxHash:            TxHashColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
