//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Epoch = newEpochTable("public", "epoch", "")

type epochTable struct {
	postgres.Table

	// Columns
	ApplicationID        postgres.ColumnInteger
	Index                postgres.ColumnFloat
	FirstBlock           postgres.ColumnFloat
	LastBlock            postgres.ColumnFloat
	InputIndexLowerBound postgres.ColumnFloat
	InputIndexUpperBound postgres.ColumnFloat
	MachineHash          postgres.ColumnBytea
	TxBufferDataBlock    postgres.ColumnBytea
	TxBufferProof        postgres.ColumnByteaArray
	IflagsYDataBlock     postgres.ColumnBytea
	IflagsYProof         postgres.ColumnByteaArray
	HtifTohostDataBlock  postgres.ColumnBytea
	HtifTohostProof      postgres.ColumnByteaArray
	Commitment           postgres.ColumnBytea
	CommitmentProof      postgres.ColumnByteaArray
	TournamentAddress    postgres.ColumnBytea
	ClaimTransactionHash postgres.ColumnBytea
	Status               postgres.ColumnString
	StagedAtBlock        postgres.ColumnFloat
	VirtualIndex         postgres.ColumnFloat
	CreatedAt            postgres.ColumnTimestampz
	UpdatedAt            postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EpochTable struct {
	epochTable

	EXCLUDED epochTable
}

// AS creates new EpochTable with assigned alias
func (a EpochTable) AS(alias string) *EpochTable {
	return newEpochTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EpochTable with assigned schema name
func (a EpochTable) FromSchema(schemaName string) *EpochTable {
	return newEpochTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EpochTable with assigned table prefix
func (a EpochTable) WithPrefix(prefix string) *EpochTable {
	return newEpochTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EpochTable with assigned table suffix
func (a EpochTable) WithSuffix(suffix string) *EpochTable {
	return newEpochTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEpochTable(schemaName, tableName, alias string) *EpochTable {
	return &EpochTable{
		epochTable: newEpochTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newEpochTableImpl("", "excluded", ""),
	}
}

func newEpochTableImpl(schemaName, tableName, alias string) epochTable {
	var (
		ApplicationIDColumn        = postgres.IntegerColumn("application_id")
		IndexColumn                = postgres.FloatColumn("index")
		FirstBlockColumn           = postgres.FloatColumn("first_block")
		LastBlockColumn            = postgres.FloatColumn("last_block")
		InputIndexLowerBoundColumn = postgres.FloatColumn("input_index_lower_bound")
		InputIndexUpperBoundColumn = postgres.FloatColumn("input_index_upper_bound")
		MachineHashColumn          = postgres.ByteaColumn("machine_hash")
		TxBufferDataBlockColumn    = postgres.ByteaColumn("tx_buffer_data_block")
		TxBufferProofColumn        = postgres.ByteaArrayColumn("tx_buffer_proof")
		IflagsYDataBlockColumn     = postgres.ByteaColumn("iflags_y_data_block")
		IflagsYProofColumn         = postgres.ByteaArrayColumn("iflags_y_proof")
		HtifTohostDataBlockColumn  = postgres.ByteaColumn("htif_tohost_data_block")
		HtifTohostProofColumn      = postgres.ByteaArrayColumn("htif_tohost_proof")
		CommitmentColumn           = postgres.ByteaColumn("commitment")
		CommitmentProofColumn      = postgres.ByteaArrayColumn("commitment_proof")
		TournamentAddressColumn    = postgres.ByteaColumn("tournament_address")
		ClaimTransactionHashColumn = postgres.ByteaColumn("claim_transaction_hash")
		StatusColumn               = postgres.StringColumn("status")
		StagedAtBlockColumn        = postgres.FloatColumn("staged_at_block")
		VirtualIndexColumn         = postgres.FloatColumn("virtual_index")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn            = postgres.TimestampzColumn("updated_at")
		allColumns                 = postgres.ColumnList{ApplicationIDColumn, IndexColumn, FirstBlockColumn, LastBlockColumn, InputIndexLowerBoundColumn, InputIndexUpperBoundColumn, MachineHashColumn, TxBufferDataBlockColumn, TxBufferProofColumn, IflagsYDataBlockColumn, IflagsYProofColumn, HtifTohostDataBlockColumn, HtifTohostProofColumn, CommitmentColumn, CommitmentProofColumn, TournamentAddressColumn, ClaimTransactionHashColumn, StatusColumn, StagedAtBlockColumn, VirtualIndexColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns             = postgres.ColumnList{FirstBlockColumn, LastBlockColumn, InputIndexLowerBoundColumn, InputIndexUpperBoundColumn, MachineHashColumn, TxBufferDataBlockColumn, TxBufferProofColumn, IflagsYDataBlockColumn, IflagsYProofColumn, HtifTohostDataBlockColumn, HtifTohostProofColumn, CommitmentColumn, CommitmentProofColumn, TournamentAddressColumn, ClaimTransactionHashColumn, StatusColumn, StagedAtBlockColumn, VirtualIndexColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns             = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return epochTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID:        ApplicationIDColumn,
		Index:                IndexColumn,
		FirstBlock:           FirstBlockColumn,
		LastBlock:            LastBlockColumn,
		InputIndexLowerBound: InputIndexLowerBoundColumn,
		InputIndexUpperBound: InputIndexUpperBoundColumn,
		MachineHash:          MachineHashColumn,
		TxBufferDataBlock:    TxBufferDataBlockColumn,
		TxBufferProof:        TxBufferProofColumn,
		IflagsYDataBlock:     IflagsYDataBlockColumn,
		IflagsYProof:         IflagsYProofColumn,
		HtifTohostDataBlock:  HtifTohostDataBlockColumn,
		HtifTohostProof:      HtifTohostProofColumn,
		Commitment:           CommitmentColumn,
		CommitmentProof:      CommitmentProofColumn,
		TournamentAddress:    TournamentAddressColumn,
		ClaimTransactionHash: ClaimTransactionHashColumn,
		Status:               StatusColumn,
		StagedAtBlock:        StagedAtBlockColumn,
		VirtualIndex:         VirtualIndexColumn,
		CreatedAt:            CreatedAtColumn,
		UpdatedAt:            UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
