//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MatchAdvances = newMatchAdvancesTable("public", "match_advances", "")

type matchAdvancesTable struct {
	postgres.Table

	// Columns
	ApplicationID     postgres.ColumnInteger
	EpochIndex        postgres.ColumnFloat
	TournamentAddress postgres.ColumnBytea
	IDHash            postgres.ColumnBytea
	OtherParent       postgres.ColumnBytea
	LeftNode          postgres.ColumnBytea
	BlockNumber       postgres.ColumnFloat
	TxHash            postgres.ColumnBytea
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MatchAdvancesTable struct {
	matchAdvancesTable

	EXCLUDED matchAdvancesTable
}

// AS creates new MatchAdvancesTable with assigned alias
func (a MatchAdvancesTable) AS(alias string) *MatchAdvancesTable {
	return newMatchAdvancesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MatchAdvancesTable with assigned schema name
func (a MatchAdvancesTable) FromSchema(schemaName string) *MatchAdvancesTable {
	return newMatchAdvancesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MatchAdvancesTable with assigned table prefix
func (a MatchAdvancesTable) WithPrefix(prefix string) *MatchAdvancesTable {
	return newMatchAdvancesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MatchAdvancesTable with assigned table suffix
func (a MatchAdvancesTable) WithSuffix(suffix string) *MatchAdvancesTable {
	return newMatchAdvancesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMatchAdvancesTable(schemaName, tableName, alias string) *MatchAdvancesTable {
	return &MatchAdvancesTable{
		matchAdvancesTable: newMatchAdvancesTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newMatchAdvancesTableImpl("", "excluded", ""),
	}
}

func newMatchAdvancesTableImpl(schemaName, tableName, alias string) matchAdvancesTable {
	var (
		ApplicationIDColumn     = postgres.IntegerColumn("application_id")
		EpochIndexColumn        = postgres.FloatColumn("epoch_index")
		TournamentAddressColumn = postgres.ByteaColumn("tournament_address")
		IDHashColumn            = postgres.ByteaColumn("id_hash")
		OtherParentColumn       = postgres.ByteaColumn("other_parent")
		LeftNodeColumn          = postgres.ByteaColumn("left_node")
		BlockNumberColumn       = postgres.FloatColumn("block_number")
		TxHashColumn            = postgres.ByteaColumn("tx_hash")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		allColumns              = postgres.ColumnList{ApplicationIDColumn, EpochIndexColumn, TournamentAddressColumn, IDHashColumn, OtherParentColumn, LeftNodeColumn, BlockNumberColumn, TxHashColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{LeftNodeColumn, BlockNumberColumn, TxHashColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return matchAdvancesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID:     ApplicationIDColumn,
		EpochIndex:        EpochIndexColumn,
		TournamentAddress: TournamentAddressColumn,
		IDHash:            IDHashColumn,
		OtherParent:       OtherParentColumn,
		LeftNode:          LeftNodeColumn,
		BlockNumber:       BlockNumberColumn,
		TxHash:            TxHashColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
