//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Matches = newMatchesTable("public", "matches", "")

type matchesTable struct {
	postgres.Table

	// Columns
	ApplicationID     postgres.ColumnInteger
	EpochIndex        postgres.ColumnFloat
	TournamentAddress postgres.ColumnString
	IDHash            postgres.ColumnString
	CommitmentOne     postgres.ColumnString
	CommitmentTwo     postgres.ColumnString
	WinnerCommitment  postgres.ColumnString
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type MatchesTable struct {
	matchesTable

	EXCLUDED matchesTable
}

// AS creates new MatchesTable with assigned alias
func (a MatchesTable) AS(alias string) *MatchesTable {
	return newMatchesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MatchesTable with assigned schema name
func (a MatchesTable) FromSchema(schemaName string) *MatchesTable {
	return newMatchesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MatchesTable with assigned table prefix
func (a MatchesTable) WithPrefix(prefix string) *MatchesTable {
	return newMatchesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MatchesTable with assigned table suffix
func (a MatchesTable) WithSuffix(suffix string) *MatchesTable {
	return newMatchesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMatchesTable(schemaName, tableName, alias string) *MatchesTable {
	return &MatchesTable{
		matchesTable: newMatchesTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newMatchesTableImpl("", "excluded", ""),
	}
}

func newMatchesTableImpl(schemaName, tableName, alias string) matchesTable {
	var (
		ApplicationIDColumn     = postgres.IntegerColumn("application_id")
		EpochIndexColumn        = postgres.FloatColumn("epoch_index")
		TournamentAddressColumn = postgres.StringColumn("tournament_address")
		IDHashColumn            = postgres.StringColumn("id_hash")
		CommitmentOneColumn     = postgres.StringColumn("commitment_one")
		CommitmentTwoColumn     = postgres.StringColumn("commitment_two")
		WinnerCommitmentColumn  = postgres.StringColumn("winner_commitment")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		allColumns              = postgres.ColumnList{ApplicationIDColumn, EpochIndexColumn, TournamentAddressColumn, IDHashColumn, CommitmentOneColumn, CommitmentTwoColumn, WinnerCommitmentColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{CommitmentOneColumn, CommitmentTwoColumn, WinnerCommitmentColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return matchesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID:     ApplicationIDColumn,
		EpochIndex:        EpochIndexColumn,
		TournamentAddress: TournamentAddressColumn,
		IDHash:            IDHashColumn,
		CommitmentOne:     CommitmentOneColumn,
		CommitmentTwo:     CommitmentTwoColumn,
		WinnerCommitment:  WinnerCommitmentColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
