//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var StateHashes = newStateHashesTable("public", "state_hashes", "")

type stateHashesTable struct {
	postgres.Table

	// Columns
	InputEpochApplicationID postgres.ColumnInteger
	EpochIndex              postgres.ColumnFloat
	InputIndex              postgres.ColumnFloat
	Index                   postgres.ColumnFloat
	MachineHash             postgres.ColumnString
	Repetitions             postgres.ColumnInteger
	CreatedAt               postgres.ColumnTimestampz
	UpdatedAt               postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type StateHashesTable struct {
	stateHashesTable

	EXCLUDED stateHashesTable
}

// AS creates new StateHashesTable with assigned alias
func (a StateHashesTable) AS(alias string) *StateHashesTable {
	return newStateHashesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new StateHashesTable with assigned schema name
func (a StateHashesTable) FromSchema(schemaName string) *StateHashesTable {
	return newStateHashesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new StateHashesTable with assigned table prefix
func (a StateHashesTable) WithPrefix(prefix string) *StateHashesTable {
	return newStateHashesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new StateHashesTable with assigned table suffix
func (a StateHashesTable) WithSuffix(suffix string) *StateHashesTable {
	return newStateHashesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newStateHashesTable(schemaName, tableName, alias string) *StateHashesTable {
	return &StateHashesTable{
		stateHashesTable: newStateHashesTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newStateHashesTableImpl("", "excluded", ""),
	}
}

func newStateHashesTableImpl(schemaName, tableName, alias string) stateHashesTable {
	var (
		InputEpochApplicationIDColumn = postgres.IntegerColumn("input_epoch_application_id")
		EpochIndexColumn              = postgres.FloatColumn("epoch_index")
		InputIndexColumn              = postgres.FloatColumn("input_index")
		IndexColumn                   = postgres.FloatColumn("index")
		MachineHashColumn             = postgres.StringColumn("machine_hash")
		RepetitionsColumn             = postgres.IntegerColumn("repetitions")
		CreatedAtColumn               = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn               = postgres.TimestampzColumn("updated_at")
		allColumns                    = postgres.ColumnList{InputEpochApplicationIDColumn, EpochIndexColumn, InputIndexColumn, IndexColumn, MachineHashColumn, RepetitionsColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns                = postgres.ColumnList{InputIndexColumn, MachineHashColumn, RepetitionsColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return stateHashesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		InputEpochApplicationID: InputEpochApplicationIDColumn,
		EpochIndex:              EpochIndexColumn,
		InputIndex:              InputIndexColumn,
		Index:                   IndexColumn,
		MachineHash:             MachineHashColumn,
		Repetitions:             RepetitionsColumn,
		CreatedAt:               CreatedAtColumn,
		UpdatedAt:               UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
