//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Tournaments = newTournamentsTable("public", "tournaments", "")

type tournamentsTable struct {
	postgres.Table

	// Columns
	ApplicationID           postgres.ColumnInteger
	EpochIndex              postgres.ColumnFloat
	Address                 postgres.ColumnString
	ParentTournamentAddress postgres.ColumnString
	ParentMatchIDHash       postgres.ColumnString
	MaxLevel                postgres.ColumnInteger
	Level                   postgres.ColumnInteger
	Log2step                postgres.ColumnInteger
	Height                  postgres.ColumnInteger
	WinnerCommitment        postgres.ColumnString
	FinalStateHash          postgres.ColumnString
	FinishedAtBlock         postgres.ColumnFloat
	CreatedAt               postgres.ColumnTimestampz
	UpdatedAt               postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TournamentsTable struct {
	tournamentsTable

	EXCLUDED tournamentsTable
}

// AS creates new TournamentsTable with assigned alias
func (a TournamentsTable) AS(alias string) *TournamentsTable {
	return newTournamentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TournamentsTable with assigned schema name
func (a TournamentsTable) FromSchema(schemaName string) *TournamentsTable {
	return newTournamentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TournamentsTable with assigned table prefix
func (a TournamentsTable) WithPrefix(prefix string) *TournamentsTable {
	return newTournamentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TournamentsTable with assigned table suffix
func (a TournamentsTable) WithSuffix(suffix string) *TournamentsTable {
	return newTournamentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTournamentsTable(schemaName, tableName, alias string) *TournamentsTable {
	return &TournamentsTable{
		tournamentsTable: newTournamentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTournamentsTableImpl("", "excluded", ""),
	}
}

func newTournamentsTableImpl(schemaName, tableName, alias string) tournamentsTable {
	var (
		ApplicationIDColumn           = postgres.IntegerColumn("application_id")
		EpochIndexColumn              = postgres.FloatColumn("epoch_index")
		AddressColumn                 = postgres.StringColumn("address")
		ParentTournamentAddressColumn = postgres.StringColumn("parent_tournament_address")
		ParentMatchIDHashColumn       = postgres.StringColumn("parent_match_id_hash")
		MaxLevelColumn                = postgres.IntegerColumn("max_level")
		LevelColumn                   = postgres.IntegerColumn("level")
		Log2stepColumn                = postgres.IntegerColumn("log2step")
		HeightColumn                  = postgres.IntegerColumn("height")
		WinnerCommitmentColumn        = postgres.StringColumn("winner_commitment")
		FinalStateHashColumn          = postgres.StringColumn("final_state_hash")
		FinishedAtBlockColumn         = postgres.FloatColumn("finished_at_block")
		CreatedAtColumn               = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn               = postgres.TimestampzColumn("updated_at")
		allColumns                    = postgres.ColumnList{ApplicationIDColumn, EpochIndexColumn, AddressColumn, ParentTournamentAddressColumn, ParentMatchIDHashColumn, MaxLevelColumn, LevelColumn, Log2stepColumn, HeightColumn, WinnerCommitmentColumn, FinalStateHashColumn, FinishedAtBlockColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns                = postgres.ColumnList{ParentTournamentAddressColumn, ParentMatchIDHashColumn, MaxLevelColumn, LevelColumn, Log2stepColumn, HeightColumn, WinnerCommitmentColumn, FinalStateHashColumn, FinishedAtBlockColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return tournamentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID:           ApplicationIDColumn,
		EpochIndex:              EpochIndexColumn,
		Address:                 AddressColumn,
		ParentTournamentAddress: ParentTournamentAddressColumn,
		ParentMatchIDHash:       ParentMatchIDHashColumn,
		MaxLevel:                MaxLevelColumn,
		Level:                   LevelColumn,
		Log2step:                Log2stepColumn,
		Height:                  HeightColumn,
		WinnerCommitment:        WinnerCommitmentColumn,
		FinalStateHash:          FinalStateHashColumn,
		FinishedAtBlock:         FinishedAtBlockColumn,
		CreatedAt:               CreatedAtColumn,
		UpdatedAt:               UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
