//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Withdrawal = newWithdrawalTable("public", "withdrawal", "")

type withdrawalTable struct {
	postgres.Table

	// Columns
	ApplicationID   postgres.ColumnInteger
	AccountIndex    postgres.ColumnFloat
	Account         postgres.ColumnBytea
	Output          postgres.ColumnBytea
	BlockNumber     postgres.ColumnFloat
	TransactionHash postgres.ColumnBytea
	LogIndex        postgres.ColumnInteger
	CreatedAt       postgres.ColumnTimestampz
	UpdatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type WithdrawalTable struct {
	withdrawalTable

	EXCLUDED withdrawalTable
}

// AS creates new WithdrawalTable with assigned alias
func (a WithdrawalTable) AS(alias string) *WithdrawalTable {
	return newWithdrawalTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WithdrawalTable with assigned schema name
func (a WithdrawalTable) FromSchema(schemaName string) *WithdrawalTable {
	return newWithdrawalTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WithdrawalTable with assigned table prefix
func (a WithdrawalTable) WithPrefix(prefix string) *WithdrawalTable {
	return newWithdrawalTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WithdrawalTable with assigned table suffix
func (a WithdrawalTable) WithSuffix(suffix string) *WithdrawalTable {
	return newWithdrawalTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWithdrawalTable(schemaName, tableName, alias string) *WithdrawalTable {
	return &WithdrawalTable{
		withdrawalTable: newWithdrawalTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newWithdrawalTableImpl("", "excluded", ""),
	}
}

func newWithdrawalTableImpl(schemaName, tableName, alias string) withdrawalTable {
	var (
		ApplicationIDColumn   = postgres.IntegerColumn("application_id")
		AccountIndexColumn    = postgres.FloatColumn("account_index")
		AccountColumn         = postgres.ByteaColumn("account")
		OutputColumn          = postgres.ByteaColumn("output")
		BlockNumberColumn     = postgres.FloatColumn("block_number")
		TransactionHashColumn = postgres.ByteaColumn("transaction_hash")
		LogIndexColumn        = postgres.IntegerColumn("log_index")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampzColumn("updated_at")
		allColumns            = postgres.ColumnList{ApplicationIDColumn, AccountIndexColumn, AccountColumn, OutputColumn, BlockNumberColumn, TransactionHashColumn, LogIndexColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{AccountColumn, OutputColumn, BlockNumberColumn, TransactionHashColumn, LogIndexColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return withdrawalTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ApplicationID:   ApplicationIDColumn,
		AccountIndex:    AccountIndexColumn,
		Account:         AccountColumn,
		Output:          OutputColumn,
		BlockNumber:     BlockNumberColumn,
		TransactionHash: TransactionHashColumn,
		LogIndex:        LogIndexColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
