// Code generated by internal/config/generate.
// DO NOT EDIT.

// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

package config

func getCartesiAuthAwsKmsKeyId() *string {
	v := getOptional("CARTESI_AUTH_AWS_KMS_KEY_ID", "", false, true, toString)
	return v
}

func getCartesiAuthAwsKmsRegion() *string {
	v := getOptional("CARTESI_AUTH_AWS_KMS_REGION", "", false, true, toString)
	return v
}

func getCartesiAuthMnemonic() *string {
	v := getOptional("CARTESI_AUTH_MNEMONIC", "", false, true, toString)
	return v
}

func getCartesiAuthMnemonicAccountIndex() *int {
	v := getOptional("CARTESI_AUTH_MNEMONIC_ACCOUNT_INDEX", "0", true, true, toInt)
	return v
}

func getCartesiAuthMnemonicFile() *string {
	v := getOptional("CARTESI_AUTH_MNEMONIC_FILE", "", false, true, toString)
	return v
}
