// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

package main

import (
	"bytes"
	"os"
	"strings"
	"text/template"

	"go/format"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// generateCodeFile generates a Go file with the getters for the config variables.
func generateCodeFile(path string, env []Env) {
	// Load template
	funcMap := template.FuncMap{
		"toFunctionName": func(env string) string {
			caser := cases.Title(language.English)
			words := strings.Split(env, "_")
			for i, word := range words {
				words[i] = caser.String(word)
			}
			return strings.Join(words[1:], "")
		},
		"toGoFunc": func(goType string) string {
			return "to" + strings.ToUpper(goType[:1]) + goType[1:]
		},
	}
	tmpl := template.Must(template.New("code").Funcs(funcMap).Parse(codeTemplate))

	// Execute template
	var buff bytes.Buffer
	err := tmpl.Execute(&buff, env)
	if err != nil {
		panic(err)
	}

	// Format code
	code, err := format.Source(buff.Bytes())
	if err != nil {
		panic(err)
	}

	// Write file
	var perm os.FileMode = 0644
	err = os.WriteFile(path, code, perm)
	if err != nil {
		panic(err)
	}
}

const codeTemplate string = `// Code generated by internal/config/generate.
// DO NOT EDIT.

// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

package config

import (
	"fmt"
	"log/slog"
	"os"
	"strconv"
	"time"

	"github.com/cartesi/rollups-node/internal/model"
)

type (
	Duration     = time.Duration
	LogLevel     = slog.Level
	DefaultBlock = model.DefaultBlock
)

// ------------------------------------------------------------------------------------------------
// Auth Kind
// ------------------------------------------------------------------------------------------------

type AuthKind uint8

const (
	AuthKindPrivateKeyVar AuthKind = iota
	AuthKindPrivateKeyFile
	AuthKindMnemonicVar
	AuthKindMnemonicFile
	AuthKindAWS
)

// ------------------------------------------------------------------------------------------------
// Parsing functions
// ------------------------------------------------------------------------------------------------

func ToInt64FromString(s string) (int64, error) {
	return strconv.ParseInt(s, 10, 64)
}

func ToUint64FromString(s string) (uint64, error) {
       value, err := strconv.ParseUint(s, 10, 64)
       return value, err
}

func ToStringFromString(s string) (string, error) {
	return s, nil
}

func ToDurationFromSeconds(s string) (time.Duration, error) {
	return time.ParseDuration(s + "s")
}

func ToLogLevelFromString(s string) (LogLevel, error) {
	var m = map[string]LogLevel{
		"debug": slog.LevelDebug,
		"info":  slog.LevelInfo,
		"warn":  slog.LevelWarn,
		"error": slog.LevelError,
	}
	if v, ok := m[s]; ok {
		return v, nil
	} else {
		var zeroValue LogLevel
		return zeroValue, fmt.Errorf("invalid log level '%s'", s)
	}
}

func ToDefaultBlockFromString(s string) (DefaultBlock,error){
	var m = map[string]DefaultBlock{
		"latest"   :  model.DefaultBlockStatusLatest,
		"pending"  :  model.DefaultBlockStatusPending,
		"safe"     :  model.DefaultBlockStatusSafe,
		"finalized":  model.DefaultBlockStatusFinalized,
	}
	if v, ok := m[s]; ok {
		return v, nil
	} else {
		var zeroValue DefaultBlock
		return zeroValue, fmt.Errorf("invalid default block '%s'", s)
	}
}

func ToAuthKindFromString(s string) (AuthKind, error) {
	var m = map[string]AuthKind{
		"private_key":      AuthKindPrivateKeyVar,
		"private_key_file": AuthKindPrivateKeyFile,
		"mnemonic":         AuthKindMnemonicVar,
		"mnemonic_file":    AuthKindMnemonicFile,
		"aws":              AuthKindAWS,
	}
	if v, ok := m[s]; ok {
		return v, nil
	} else {
		var zeroValue AuthKind
		return zeroValue, fmt.Errorf("invalid auth kind '%s'", s)
	}
}

// Aliases to be used by the generated functions.
var (
	toBool         = strconv.ParseBool
	toInt          = strconv.Atoi
	toInt64        = ToInt64FromString
	toUint64       = ToUint64FromString
	toString       = ToStringFromString
	toDuration     = ToDurationFromSeconds
	toLogLevel     = ToLogLevelFromString
	toAuthKind     = ToAuthKindFromString
	toDefaultBlock = ToDefaultBlockFromString
)

// ------------------------------------------------------------------------------------------------
// Getters
// ------------------------------------------------------------------------------------------------

{{range .}}
func Get{{toFunctionName .Name}}() {{.GoType}} {
	s, ok := os.LookupEnv("{{.Name}}")
	if !ok {
		{{- if .Default}}
		s = "{{.Default}}"
		{{- else}}
		panic("missing env var {{.Name}}")
		{{- end}}
	}
	val, err := {{toGoFunc .GoType}}(s)
	if err != nil {
		panic(fmt.Sprintf("failed to parse {{.Name}}: %v", err))
	}
	return val
}
{{end}}`
