// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

package main

import (
	"os"
	"text/template"
)

// generateDocsFile generates a Markdown file with the documentation of the config variables.
func generateDocsFile(path string, env []Env) {
	// Open output file
	file, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	// Load template
	funcMap := template.FuncMap{
		"backtick": func(s string) string {
			return "`" + s + "`"
		},
		"quote": func(s string) string {
			return `"` + s + `"`
		},
	}
	tmpl := template.Must(template.New("docs").Funcs(funcMap).Parse(docsTemplate))

	// Execute template
	err = tmpl.Execute(file, env)
	if err != nil {
		panic(err)
	}
}

const docsTemplate string = `<!--
File generated by internal/config/generate.
DO NOT EDIT.
-->

<!-- markdownlint-disable line_length -->
# Node Configuration

The node is configurable through environment variables.
Variables prefixed CARTESI_ are listed below. A few subsystems additionally read
standard variables defined by third-party SDKs; those are listed at the end.

This file documents the configuration options.

<!-- markdownlint-disable MD012 -->
{{- range .}}

## {{backtick .Name}}

{{.Description}}

* **Type:** {{backtick .GoType}}
{{- if .Default}}
* **Default:** {{.Default | quote | backtick}}
{{- end}}
{{- if .File}}
* **File variant:** {{printf "%s_FILE" .Name | backtick}} reads the value from a file.
  The file must be a regular file matching one of the canonical forms:
  {{backtick "0400"}} or {{backtick "0600"}} owned by the node's user (Compose / host files), or
  {{backtick "0440"}} owned by root with the node's group (Kubernetes {{backtick "fsGroup"}}).
  Symlinks, directories, FIFOs, and device nodes are rejected. The node
  refuses to start otherwise.
{{- end}}
{{- if .UsedBy}}
* **Used by:** {{range $i, $e := .UsedBy}}{{if $i}}, {{end}}{{$e}}{{end}}
{{- end}}
{{- end}}

## Externally-provided configuration

These are read by the AWS SDK, not by the node's own configuration layer, and
apply only when CARTESI_AUTH_KIND=aws.

* AWS_REGION / AWS_DEFAULT_REGION — region used to resolve the KMS key.
* AWS_ENDPOINT_URL_KMS / AWS_ENDPOINT_URL — override the KMS endpoint
  (VPC endpoint, PrivateLink, FIPS, or a local emulator such as LocalStack).
* AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_SESSION_TOKEN — static
  credentials. They may instead come from the shared config file, an EC2 instance
  profile, or IRSA; the node does not require any particular source.

Full resolution order is documented by AWS; the node applies no overrides.
`
