// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

package deposit

import (
	"bytes"
	"context"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"

	"github.com/cartesi/rollups-node/pkg/contracts/iapplication"
	"github.com/cartesi/rollups-node/pkg/contracts/iinputbox"
	"github.com/cartesi/rollups-node/pkg/contracts/inputs"
)

// verifyDepositReceipt checks the input generated by the portal, not token
// Transfer events, which can also occur during other calls in the transaction.
func verifyDepositReceipt(
	ctx context.Context,
	client *ethclient.Client,
	receipt *types.Receipt,
	application, portal common.Address,
	payload []byte,
) error {
	app, err := iapplication.NewIApplication(application, client)
	if err != nil {
		return err
	}
	inputBoxAddress, err := app.GetInputBox(&bind.CallOpts{Context: ctx, BlockNumber: receipt.BlockNumber})
	if err != nil {
		return fmt.Errorf("read application InputBox at receipt block: %w", err)
	}
	if inputBoxAddress == (common.Address{}) {
		return fmt.Errorf("application returned a zero InputBox address")
	}
	inputBox, err := iinputbox.NewIInputBox(inputBoxAddress, client)
	if err != nil {
		return err
	}
	inputABI, err := inputs.InputsMetaData.GetAbi()
	if err != nil {
		return err
	}
	advance := inputABI.Methods["EvmAdvance"]
	for _, log := range receipt.Logs {
		if log == nil || log.Address != inputBoxAddress {
			continue
		}
		event, err := inputBox.ParseInputAdded(*log)
		if err != nil || event.AppContract != application || !bytes.HasPrefix(event.Input, advance.ID) {
			continue
		}
		args := make(map[string]any)
		if err := advance.Inputs.UnpackIntoMap(args, event.Input[len(advance.ID):]); err != nil {
			continue
		}
		inputPayload, ok := args["payload"].([]byte)
		index, indexOK := args["index"].(*big.Int)
		if ok && indexOK && index.Cmp(event.Index) == 0 && args["appContract"] == application && args["msgSender"] == portal &&
			bytes.Equal(inputPayload, payload) {
			return nil
		}
	}
	return fmt.Errorf("receipt has no matching deposit InputAdded event")
}
