// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package readerclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type CompletionStatus string

const (
	CompletionStatusUnprocessed                CompletionStatus = "UNPROCESSED"
	CompletionStatusAccepted                   CompletionStatus = "ACCEPTED"
	CompletionStatusRejected                   CompletionStatus = "REJECTED"
	CompletionStatusException                  CompletionStatus = "EXCEPTION"
	CompletionStatusMachineHalted              CompletionStatus = "MACHINE_HALTED"
	CompletionStatusCycleLimitExceeded         CompletionStatus = "CYCLE_LIMIT_EXCEEDED"
	CompletionStatusTimeLimitExceeded          CompletionStatus = "TIME_LIMIT_EXCEEDED"
	CompletionStatusPayloadLengthLimitExceeded CompletionStatus = "PAYLOAD_LENGTH_LIMIT_EXCEEDED"
)

// __getInputInput is used internally by genqlient
type __getInputInput struct {
	Index int `json:"index"`
}

// GetIndex returns __getInputInput.Index, and is useful for accessing the field via an interface.
func (v *__getInputInput) GetIndex() int { return v.Index }

// getInputInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getInputInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
	// Status of the input
	Status CompletionStatus `json:"status"`
	// Address responsible for submitting the input
	MsgSender string `json:"msgSender"`
	// Timestamp associated with the input submission, as defined by the base layer's block in which it was recorded
	Timestamp string `json:"timestamp"`
	// Number of the base layer block in which the input was recorded
	BlockNumber string `json:"blockNumber"`
	// Input payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
}

// GetIndex returns getInputInput.Index, and is useful for accessing the field via an interface.
func (v *getInputInput) GetIndex() int { return v.Index }

// GetStatus returns getInputInput.Status, and is useful for accessing the field via an interface.
func (v *getInputInput) GetStatus() CompletionStatus { return v.Status }

// GetMsgSender returns getInputInput.MsgSender, and is useful for accessing the field via an interface.
func (v *getInputInput) GetMsgSender() string { return v.MsgSender }

// GetTimestamp returns getInputInput.Timestamp, and is useful for accessing the field via an interface.
func (v *getInputInput) GetTimestamp() string { return v.Timestamp }

// GetBlockNumber returns getInputInput.BlockNumber, and is useful for accessing the field via an interface.
func (v *getInputInput) GetBlockNumber() string { return v.BlockNumber }

// GetPayload returns getInputInput.Payload, and is useful for accessing the field via an interface.
func (v *getInputInput) GetPayload() string { return v.Payload }

// getInputResponse is returned by getInput on success.
type getInputResponse struct {
	// Get input based on its identifier
	Input getInputInput `json:"input"`
}

// GetInput returns getInputResponse.Input, and is useful for accessing the field via an interface.
func (v *getInputResponse) GetInput() getInputInput { return v.Input }

// getInputsInputsInputConnection includes the requested fields of the GraphQL type InputConnection.
// The GraphQL type's documentation follows.
//
// Pagination result
type getInputsInputsInputConnection struct {
	// Pagination entries returned for the current page
	Edges []getInputsInputsInputConnectionEdgesInputEdge `json:"edges"`
}

// GetEdges returns getInputsInputsInputConnection.Edges, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnection) GetEdges() []getInputsInputsInputConnectionEdgesInputEdge {
	return v.Edges
}

// getInputsInputsInputConnectionEdgesInputEdge includes the requested fields of the GraphQL type InputEdge.
// The GraphQL type's documentation follows.
//
// Pagination entry
type getInputsInputsInputConnectionEdgesInputEdge struct {
	// Node instance
	Node getInputsInputsInputConnectionEdgesInputEdgeNodeInput `json:"node"`
}

// GetNode returns getInputsInputsInputConnectionEdgesInputEdge.Node, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdge) GetNode() getInputsInputsInputConnectionEdgesInputEdgeNodeInput {
	return v.Node
}

// getInputsInputsInputConnectionEdgesInputEdgeNodeInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getInputsInputsInputConnectionEdgesInputEdgeNodeInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
	// Status of the input
	Status CompletionStatus `json:"status"`
	// Address responsible for submitting the input
	MsgSender string `json:"msgSender"`
	// Timestamp associated with the input submission, as defined by the base layer's block in which it was recorded
	Timestamp string `json:"timestamp"`
	// Number of the base layer block in which the input was recorded
	BlockNumber string `json:"blockNumber"`
	// Input payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
}

// GetIndex returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Index, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetIndex() int { return v.Index }

// GetStatus returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Status, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetStatus() CompletionStatus {
	return v.Status
}

// GetMsgSender returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.MsgSender, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetMsgSender() string {
	return v.MsgSender
}

// GetTimestamp returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Timestamp, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetTimestamp() string {
	return v.Timestamp
}

// GetBlockNumber returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.BlockNumber, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetBlockNumber() string {
	return v.BlockNumber
}

// GetPayload returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Payload, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetPayload() string { return v.Payload }

// getInputsResponse is returned by getInputs on success.
type getInputsResponse struct {
	// Get inputs with support for pagination
	Inputs getInputsInputsInputConnection `json:"inputs"`
}

// GetInputs returns getInputsResponse.Inputs, and is useful for accessing the field via an interface.
func (v *getInputsResponse) GetInputs() getInputsInputsInputConnection { return v.Inputs }

// getNoticeNotice includes the requested fields of the GraphQL type Notice.
// The GraphQL type's documentation follows.
//
// Informational statement that can be validated in the base layer blockchain
type getNoticeNotice struct {
	// Notice index within the context of the input that produced it
	Index int `json:"index"`
	// Notice data as a payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Proof object that allows this notice to be validated by the base layer blockchain
	Proof getNoticeNoticeProof `json:"proof"`
	// Input whose processing produced the notice
	Input getNoticeNoticeInput `json:"input"`
}

// GetIndex returns getNoticeNotice.Index, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetIndex() int { return v.Index }

// GetPayload returns getNoticeNotice.Payload, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetPayload() string { return v.Payload }

// GetProof returns getNoticeNotice.Proof, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetProof() getNoticeNoticeProof { return v.Proof }

// GetInput returns getNoticeNotice.Input, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetInput() getNoticeNoticeInput { return v.Input }

// getNoticeNoticeInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getNoticeNoticeInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
}

// GetIndex returns getNoticeNoticeInput.Index, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeInput) GetIndex() int { return v.Index }

// getNoticeNoticeProof includes the requested fields of the GraphQL type Proof.
// The GraphQL type's documentation follows.
//
// Data that can be used as proof to validate notices and execute vouchers on the base layer blockchain
type getNoticeNoticeProof struct {
	// Validity proof for an output
	Validity getNoticeNoticeProofValidityOutputValidityProof `json:"validity"`
	// Data that allows the validity proof to be contextualized within submitted claims, given as a payload in Ethereum hex binary format, starting with '0x'
	Context string `json:"context"`
}

// GetValidity returns getNoticeNoticeProof.Validity, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProof) GetValidity() getNoticeNoticeProofValidityOutputValidityProof {
	return v.Validity
}

// GetContext returns getNoticeNoticeProof.Context, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProof) GetContext() string { return v.Context }

// getNoticeNoticeProofValidityOutputValidityProof includes the requested fields of the GraphQL type OutputValidityProof.
// The GraphQL type's documentation follows.
//
// Validity proof for an output
type getNoticeNoticeProofValidityOutputValidityProof struct {
	// Local input index within the context of the related epoch
	InputIndexWithinEpoch int `json:"inputIndexWithinEpoch"`
	// Output index within the context of the input that produced it
	OutputIndexWithinInput int `json:"outputIndexWithinInput"`
	// Merkle root of all output hashes of the related input, given in Ethereum hex binary format (32 bytes), starting with '0x'
	OutputHashesRootHash string `json:"outputHashesRootHash"`
	// Merkle root of all voucher hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	VouchersEpochRootHash string `json:"vouchersEpochRootHash"`
	// Merkle root of all notice hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	NoticesEpochRootHash string `json:"noticesEpochRootHash"`
	// Hash of the machine state claimed for the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	MachineStateHash string `json:"machineStateHash"`
	// Proof that this output hash is in the output-hashes merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashInOutputHashesSiblings []string `json:"outputHashInOutputHashesSiblings"`
	// Proof that this output-hashes root hash is in epoch's output merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashesInEpochSiblings []string `json:"outputHashesInEpochSiblings"`
}

// GetInputIndexWithinEpoch returns getNoticeNoticeProofValidityOutputValidityProof.InputIndexWithinEpoch, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetInputIndexWithinEpoch() int {
	return v.InputIndexWithinEpoch
}

// GetOutputIndexWithinInput returns getNoticeNoticeProofValidityOutputValidityProof.OutputIndexWithinInput, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputIndexWithinInput() int {
	return v.OutputIndexWithinInput
}

// GetOutputHashesRootHash returns getNoticeNoticeProofValidityOutputValidityProof.OutputHashesRootHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputHashesRootHash() string {
	return v.OutputHashesRootHash
}

// GetVouchersEpochRootHash returns getNoticeNoticeProofValidityOutputValidityProof.VouchersEpochRootHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetVouchersEpochRootHash() string {
	return v.VouchersEpochRootHash
}

// GetNoticesEpochRootHash returns getNoticeNoticeProofValidityOutputValidityProof.NoticesEpochRootHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetNoticesEpochRootHash() string {
	return v.NoticesEpochRootHash
}

// GetMachineStateHash returns getNoticeNoticeProofValidityOutputValidityProof.MachineStateHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetMachineStateHash() string {
	return v.MachineStateHash
}

// GetOutputHashInOutputHashesSiblings returns getNoticeNoticeProofValidityOutputValidityProof.OutputHashInOutputHashesSiblings, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputHashInOutputHashesSiblings() []string {
	return v.OutputHashInOutputHashesSiblings
}

// GetOutputHashesInEpochSiblings returns getNoticeNoticeProofValidityOutputValidityProof.OutputHashesInEpochSiblings, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputHashesInEpochSiblings() []string {
	return v.OutputHashesInEpochSiblings
}

// getNoticeResponse is returned by getNotice on success.
type getNoticeResponse struct {
	// Get notice based on its index
	Notice getNoticeNotice `json:"notice"`
}

// GetNotice returns getNoticeResponse.Notice, and is useful for accessing the field via an interface.
func (v *getNoticeResponse) GetNotice() getNoticeNotice { return v.Notice }

// The query or mutation executed by getInput.
const getInput_Operation = `
query getInput ($index: Int!) {
	input(index: $index) {
		index
		status
		msgSender
		timestamp
		blockNumber
		payload
	}
}
`

func getInput(
	ctx context.Context,
	client graphql.Client,
	index int,
) (*getInputResponse, error) {
	req := &graphql.Request{
		OpName: "getInput",
		Query:  getInput_Operation,
		Variables: &__getInputInput{
			Index: index,
		},
	}
	var err error

	var data getInputResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getInputs.
const getInputs_Operation = `
query getInputs {
	inputs {
		edges {
			node {
				index
				status
				msgSender
				timestamp
				blockNumber
				payload
			}
		}
	}
}
`

func getInputs(
	ctx context.Context,
	client graphql.Client,
) (*getInputsResponse, error) {
	req := &graphql.Request{
		OpName: "getInputs",
		Query:  getInputs_Operation,
	}
	var err error

	var data getInputsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getNotice.
const getNotice_Operation = `
query getNotice ($noticeIndex: Int!, $inputIndex: Int!) {
	notice(noticeIndex: $noticeIndex, inputIndex: $inputIndex) {
		index
		payload
		proof {
			validity {
				inputIndexWithinEpoch
				outputIndexWithinInput
				outputHashesRootHash
				vouchersEpochRootHash
				noticesEpochRootHash
				machineStateHash
				outputHashInOutputHashesSiblings
				outputHashesInEpochSiblings
			}
			context
		}
		input {
			index
		}
	}
}
`

func getNotice(
	ctx context.Context,
	client graphql.Client,
	noticeIndex int,
	inputIndex int,
) (*getNoticeResponse, error) {
	req := &graphql.Request{
		OpName: "getNotice",
		Query:  getNotice_Operation,
		Variables: &__getNoticeInput{
			NoticeIndex: noticeIndex,
			InputIndex:  inputIndex,
		},
	}
	var err error

	var data getNoticeResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
