// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package readerclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type CompletionStatus string

const (
	CompletionStatusUnprocessed                CompletionStatus = "UNPROCESSED"
	CompletionStatusAccepted                   CompletionStatus = "ACCEPTED"
	CompletionStatusRejected                   CompletionStatus = "REJECTED"
	CompletionStatusException                  CompletionStatus = "EXCEPTION"
	CompletionStatusMachineHalted              CompletionStatus = "MACHINE_HALTED"
	CompletionStatusCycleLimitExceeded         CompletionStatus = "CYCLE_LIMIT_EXCEEDED"
	CompletionStatusTimeLimitExceeded          CompletionStatus = "TIME_LIMIT_EXCEEDED"
	CompletionStatusPayloadLengthLimitExceeded CompletionStatus = "PAYLOAD_LENGTH_LIMIT_EXCEEDED"
)

// __getInputInput is used internally by genqlient
type __getInputInput struct {
	Index int `json:"index"`
}

// GetIndex returns __getInputInput.Index, and is useful for accessing the field via an interface.
func (v *__getInputInput) GetIndex() int { return v.Index }

// __getInputNoticesInput is used internally by genqlient
type __getInputNoticesInput struct {
	InputIndex int `json:"inputIndex"`
}

// GetInputIndex returns __getInputNoticesInput.InputIndex, and is useful for accessing the field via an interface.
func (v *__getInputNoticesInput) GetInputIndex() int { return v.InputIndex }

// __getInputVouchersInput is used internally by genqlient
type __getInputVouchersInput struct {
	InputIndex int `json:"inputIndex"`
}

// GetInputIndex returns __getInputVouchersInput.InputIndex, and is useful for accessing the field via an interface.
func (v *__getInputVouchersInput) GetInputIndex() int { return v.InputIndex }

// __getNoticeInput is used internally by genqlient
type __getNoticeInput struct {
	NoticeIndex int `json:"noticeIndex"`
	InputIndex  int `json:"inputIndex"`
}

// GetNoticeIndex returns __getNoticeInput.NoticeIndex, and is useful for accessing the field via an interface.
func (v *__getNoticeInput) GetNoticeIndex() int { return v.NoticeIndex }

// GetInputIndex returns __getNoticeInput.InputIndex, and is useful for accessing the field via an interface.
func (v *__getNoticeInput) GetInputIndex() int { return v.InputIndex }

// __getReportInput is used internally by genqlient
type __getReportInput struct {
	ReportIndex int `json:"reportIndex"`
	InputIndex  int `json:"inputIndex"`
}

// GetReportIndex returns __getReportInput.ReportIndex, and is useful for accessing the field via an interface.
func (v *__getReportInput) GetReportIndex() int { return v.ReportIndex }

// GetInputIndex returns __getReportInput.InputIndex, and is useful for accessing the field via an interface.
func (v *__getReportInput) GetInputIndex() int { return v.InputIndex }

// __getVoucherInput is used internally by genqlient
type __getVoucherInput struct {
	VoucherIndex int `json:"voucherIndex"`
	InputIndex   int `json:"inputIndex"`
}

// GetVoucherIndex returns __getVoucherInput.VoucherIndex, and is useful for accessing the field via an interface.
func (v *__getVoucherInput) GetVoucherIndex() int { return v.VoucherIndex }

// GetInputIndex returns __getVoucherInput.InputIndex, and is useful for accessing the field via an interface.
func (v *__getVoucherInput) GetInputIndex() int { return v.InputIndex }

// getInputInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getInputInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
	// Status of the input
	Status CompletionStatus `json:"status"`
	// Address responsible for submitting the input
	MsgSender string `json:"msgSender"`
	// Timestamp associated with the input submission, as defined by the base layer's block in which it was recorded
	Timestamp string `json:"timestamp"`
	// Number of the base layer block in which the input was recorded
	BlockNumber string `json:"blockNumber"`
	// Input payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
}

// GetIndex returns getInputInput.Index, and is useful for accessing the field via an interface.
func (v *getInputInput) GetIndex() int { return v.Index }

// GetStatus returns getInputInput.Status, and is useful for accessing the field via an interface.
func (v *getInputInput) GetStatus() CompletionStatus { return v.Status }

// GetMsgSender returns getInputInput.MsgSender, and is useful for accessing the field via an interface.
func (v *getInputInput) GetMsgSender() string { return v.MsgSender }

// GetTimestamp returns getInputInput.Timestamp, and is useful for accessing the field via an interface.
func (v *getInputInput) GetTimestamp() string { return v.Timestamp }

// GetBlockNumber returns getInputInput.BlockNumber, and is useful for accessing the field via an interface.
func (v *getInputInput) GetBlockNumber() string { return v.BlockNumber }

// GetPayload returns getInputInput.Payload, and is useful for accessing the field via an interface.
func (v *getInputInput) GetPayload() string { return v.Payload }

// getInputNoticesInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getInputNoticesInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
	// Get notices from this particular input with support for pagination
	Notices getInputNoticesInputNoticesNoticeConnection `json:"notices"`
}

// GetIndex returns getInputNoticesInput.Index, and is useful for accessing the field via an interface.
func (v *getInputNoticesInput) GetIndex() int { return v.Index }

// GetNotices returns getInputNoticesInput.Notices, and is useful for accessing the field via an interface.
func (v *getInputNoticesInput) GetNotices() getInputNoticesInputNoticesNoticeConnection {
	return v.Notices
}

// getInputNoticesInputNoticesNoticeConnection includes the requested fields of the GraphQL type NoticeConnection.
// The GraphQL type's documentation follows.
//
// Pagination result
type getInputNoticesInputNoticesNoticeConnection struct {
	// Pagination entries returned for the current page
	Edges []getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdge `json:"edges"`
}

// GetEdges returns getInputNoticesInputNoticesNoticeConnection.Edges, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnection) GetEdges() []getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdge {
	return v.Edges
}

// getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdge includes the requested fields of the GraphQL type NoticeEdge.
// The GraphQL type's documentation follows.
//
// Pagination entry
type getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdge struct {
	// Node instance
	Node getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice `json:"node"`
}

// GetNode returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdge.Node, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdge) GetNode() getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice {
	return v.Node
}

// getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice includes the requested fields of the GraphQL type Notice.
// The GraphQL type's documentation follows.
//
// Informational statement that can be validated in the base layer blockchain
type getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice struct {
	// Notice index within the context of the input that produced it
	Index int `json:"index"`
	// Notice data as a payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Proof object that allows this notice to be validated by the base layer blockchain
	Proof getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof `json:"proof"`
}

// GetIndex returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice.Index, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice) GetIndex() int {
	return v.Index
}

// GetPayload returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice.Payload, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice) GetPayload() string {
	return v.Payload
}

// GetProof returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice.Proof, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice) GetProof() getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof {
	return v.Proof
}

// getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof includes the requested fields of the GraphQL type Proof.
// The GraphQL type's documentation follows.
//
// Data that can be used as proof to validate notices and execute vouchers on the base layer blockchain
type getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof struct {
	// Validity proof for an output
	Validity getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof `json:"validity"`
	// Data that allows the validity proof to be contextualized within submitted claims, given as a payload in Ethereum hex binary format, starting with '0x'
	Context string `json:"context"`
}

// GetValidity returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof.Validity, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof) GetValidity() getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof {
	return v.Validity
}

// GetContext returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof.Context, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof) GetContext() string {
	return v.Context
}

// getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof includes the requested fields of the GraphQL type OutputValidityProof.
// The GraphQL type's documentation follows.
//
// Validity proof for an output
type getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof struct {
	// Local input index within the context of the related epoch
	InputIndexWithinEpoch int `json:"inputIndexWithinEpoch"`
	// Output index within the context of the input that produced it
	OutputIndexWithinInput int `json:"outputIndexWithinInput"`
	// Merkle root of all output hashes of the related input, given in Ethereum hex binary format (32 bytes), starting with '0x'
	OutputHashesRootHash string `json:"outputHashesRootHash"`
	// Merkle root of all voucher hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	VouchersEpochRootHash string `json:"vouchersEpochRootHash"`
	// Merkle root of all notice hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	NoticesEpochRootHash string `json:"noticesEpochRootHash"`
	// Hash of the machine state claimed for the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	MachineStateHash string `json:"machineStateHash"`
	// Proof that this output hash is in the output-hashes merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashInOutputHashesSiblings []string `json:"outputHashInOutputHashesSiblings"`
	// Proof that this output-hashes root hash is in epoch's output merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashesInEpochSiblings []string `json:"outputHashesInEpochSiblings"`
}

// GetInputIndexWithinEpoch returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.InputIndexWithinEpoch, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetInputIndexWithinEpoch() int {
	return v.InputIndexWithinEpoch
}

// GetOutputIndexWithinInput returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputIndexWithinInput, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputIndexWithinInput() int {
	return v.OutputIndexWithinInput
}

// GetOutputHashesRootHash returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputHashesRootHash, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputHashesRootHash() string {
	return v.OutputHashesRootHash
}

// GetVouchersEpochRootHash returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.VouchersEpochRootHash, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetVouchersEpochRootHash() string {
	return v.VouchersEpochRootHash
}

// GetNoticesEpochRootHash returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.NoticesEpochRootHash, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetNoticesEpochRootHash() string {
	return v.NoticesEpochRootHash
}

// GetMachineStateHash returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.MachineStateHash, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetMachineStateHash() string {
	return v.MachineStateHash
}

// GetOutputHashInOutputHashesSiblings returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputHashInOutputHashesSiblings, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputHashInOutputHashesSiblings() []string {
	return v.OutputHashInOutputHashesSiblings
}

// GetOutputHashesInEpochSiblings returns getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputHashesInEpochSiblings, and is useful for accessing the field via an interface.
func (v *getInputNoticesInputNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputHashesInEpochSiblings() []string {
	return v.OutputHashesInEpochSiblings
}

// getInputNoticesResponse is returned by getInputNotices on success.
type getInputNoticesResponse struct {
	// Get input based on its identifier
	Input getInputNoticesInput `json:"input"`
}

// GetInput returns getInputNoticesResponse.Input, and is useful for accessing the field via an interface.
func (v *getInputNoticesResponse) GetInput() getInputNoticesInput { return v.Input }

// getInputResponse is returned by getInput on success.
type getInputResponse struct {
	// Get input based on its identifier
	Input getInputInput `json:"input"`
}

// GetInput returns getInputResponse.Input, and is useful for accessing the field via an interface.
func (v *getInputResponse) GetInput() getInputInput { return v.Input }

// getInputVouchersInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getInputVouchersInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
	// Get vouchers from this particular input with support for pagination
	Vouchers getInputVouchersInputVouchersVoucherConnection `json:"vouchers"`
}

// GetIndex returns getInputVouchersInput.Index, and is useful for accessing the field via an interface.
func (v *getInputVouchersInput) GetIndex() int { return v.Index }

// GetVouchers returns getInputVouchersInput.Vouchers, and is useful for accessing the field via an interface.
func (v *getInputVouchersInput) GetVouchers() getInputVouchersInputVouchersVoucherConnection {
	return v.Vouchers
}

// getInputVouchersInputVouchersVoucherConnection includes the requested fields of the GraphQL type VoucherConnection.
// The GraphQL type's documentation follows.
//
// Pagination result
type getInputVouchersInputVouchersVoucherConnection struct {
	// Pagination entries returned for the current page
	Edges []getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdge `json:"edges"`
}

// GetEdges returns getInputVouchersInputVouchersVoucherConnection.Edges, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnection) GetEdges() []getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdge {
	return v.Edges
}

// getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdge includes the requested fields of the GraphQL type VoucherEdge.
// The GraphQL type's documentation follows.
//
// Pagination entry
type getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdge struct {
	// Node instance
	Node getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher `json:"node"`
}

// GetNode returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdge.Node, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdge) GetNode() getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher {
	return v.Node
}

// getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher includes the requested fields of the GraphQL type Voucher.
// The GraphQL type's documentation follows.
//
// Representation of a transaction that can be carried out on the base layer blockchain, such as a transfer of assets
type getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher struct {
	// Voucher index within the context of the input that produced it
	Index int `json:"index"`
	// Transaction payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Transaction destination address in Ethereum hex binary format (20 bytes), starting with '0x'
	Destination string `json:"destination"`
	// Proof object that allows this voucher to be validated and executed on the base layer blockchain
	Proof getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof `json:"proof"`
}

// GetIndex returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Index, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetIndex() int {
	return v.Index
}

// GetPayload returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Payload, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetPayload() string {
	return v.Payload
}

// GetDestination returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Destination, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetDestination() string {
	return v.Destination
}

// GetProof returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Proof, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetProof() getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof {
	return v.Proof
}

// getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof includes the requested fields of the GraphQL type Proof.
// The GraphQL type's documentation follows.
//
// Data that can be used as proof to validate notices and execute vouchers on the base layer blockchain
type getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof struct {
	// Validity proof for an output
	Validity getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof `json:"validity"`
	// Data that allows the validity proof to be contextualized within submitted claims, given as a payload in Ethereum hex binary format, starting with '0x'
	Context string `json:"context"`
}

// GetValidity returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof.Validity, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof) GetValidity() getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof {
	return v.Validity
}

// GetContext returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof.Context, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof) GetContext() string {
	return v.Context
}

// getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof includes the requested fields of the GraphQL type OutputValidityProof.
// The GraphQL type's documentation follows.
//
// Validity proof for an output
type getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof struct {
	// Local input index within the context of the related epoch
	InputIndexWithinEpoch int `json:"inputIndexWithinEpoch"`
	// Output index within the context of the input that produced it
	OutputIndexWithinInput int `json:"outputIndexWithinInput"`
	// Merkle root of all output hashes of the related input, given in Ethereum hex binary format (32 bytes), starting with '0x'
	OutputHashesRootHash string `json:"outputHashesRootHash"`
	// Merkle root of all voucher hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	VouchersEpochRootHash string `json:"vouchersEpochRootHash"`
	// Merkle root of all notice hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	NoticesEpochRootHash string `json:"noticesEpochRootHash"`
	// Hash of the machine state claimed for the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	MachineStateHash string `json:"machineStateHash"`
	// Proof that this output hash is in the output-hashes merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashInOutputHashesSiblings []string `json:"outputHashInOutputHashesSiblings"`
	// Proof that this output-hashes root hash is in epoch's output merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashesInEpochSiblings []string `json:"outputHashesInEpochSiblings"`
}

// GetInputIndexWithinEpoch returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.InputIndexWithinEpoch, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetInputIndexWithinEpoch() int {
	return v.InputIndexWithinEpoch
}

// GetOutputIndexWithinInput returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputIndexWithinInput, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputIndexWithinInput() int {
	return v.OutputIndexWithinInput
}

// GetOutputHashesRootHash returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputHashesRootHash, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputHashesRootHash() string {
	return v.OutputHashesRootHash
}

// GetVouchersEpochRootHash returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.VouchersEpochRootHash, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetVouchersEpochRootHash() string {
	return v.VouchersEpochRootHash
}

// GetNoticesEpochRootHash returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.NoticesEpochRootHash, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetNoticesEpochRootHash() string {
	return v.NoticesEpochRootHash
}

// GetMachineStateHash returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.MachineStateHash, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetMachineStateHash() string {
	return v.MachineStateHash
}

// GetOutputHashInOutputHashesSiblings returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputHashInOutputHashesSiblings, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputHashInOutputHashesSiblings() []string {
	return v.OutputHashInOutputHashesSiblings
}

// GetOutputHashesInEpochSiblings returns getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputHashesInEpochSiblings, and is useful for accessing the field via an interface.
func (v *getInputVouchersInputVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputHashesInEpochSiblings() []string {
	return v.OutputHashesInEpochSiblings
}

// getInputVouchersResponse is returned by getInputVouchers on success.
type getInputVouchersResponse struct {
	// Get input based on its identifier
	Input getInputVouchersInput `json:"input"`
}

// GetInput returns getInputVouchersResponse.Input, and is useful for accessing the field via an interface.
func (v *getInputVouchersResponse) GetInput() getInputVouchersInput { return v.Input }

// getInputsInputsInputConnection includes the requested fields of the GraphQL type InputConnection.
// The GraphQL type's documentation follows.
//
// Pagination result
type getInputsInputsInputConnection struct {
	// Pagination entries returned for the current page
	Edges []getInputsInputsInputConnectionEdgesInputEdge `json:"edges"`
}

// GetEdges returns getInputsInputsInputConnection.Edges, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnection) GetEdges() []getInputsInputsInputConnectionEdgesInputEdge {
	return v.Edges
}

// getInputsInputsInputConnectionEdgesInputEdge includes the requested fields of the GraphQL type InputEdge.
// The GraphQL type's documentation follows.
//
// Pagination entry
type getInputsInputsInputConnectionEdgesInputEdge struct {
	// Node instance
	Node getInputsInputsInputConnectionEdgesInputEdgeNodeInput `json:"node"`
}

// GetNode returns getInputsInputsInputConnectionEdgesInputEdge.Node, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdge) GetNode() getInputsInputsInputConnectionEdgesInputEdgeNodeInput {
	return v.Node
}

// getInputsInputsInputConnectionEdgesInputEdgeNodeInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getInputsInputsInputConnectionEdgesInputEdgeNodeInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
	// Status of the input
	Status CompletionStatus `json:"status"`
	// Address responsible for submitting the input
	MsgSender string `json:"msgSender"`
	// Timestamp associated with the input submission, as defined by the base layer's block in which it was recorded
	Timestamp string `json:"timestamp"`
	// Number of the base layer block in which the input was recorded
	BlockNumber string `json:"blockNumber"`
	// Input payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
}

// GetIndex returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Index, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetIndex() int { return v.Index }

// GetStatus returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Status, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetStatus() CompletionStatus {
	return v.Status
}

// GetMsgSender returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.MsgSender, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetMsgSender() string {
	return v.MsgSender
}

// GetTimestamp returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Timestamp, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetTimestamp() string {
	return v.Timestamp
}

// GetBlockNumber returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.BlockNumber, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetBlockNumber() string {
	return v.BlockNumber
}

// GetPayload returns getInputsInputsInputConnectionEdgesInputEdgeNodeInput.Payload, and is useful for accessing the field via an interface.
func (v *getInputsInputsInputConnectionEdgesInputEdgeNodeInput) GetPayload() string { return v.Payload }

// getInputsResponse is returned by getInputs on success.
type getInputsResponse struct {
	// Get inputs with support for pagination
	Inputs getInputsInputsInputConnection `json:"inputs"`
}

// GetInputs returns getInputsResponse.Inputs, and is useful for accessing the field via an interface.
func (v *getInputsResponse) GetInputs() getInputsInputsInputConnection { return v.Inputs }

// getNoticeNotice includes the requested fields of the GraphQL type Notice.
// The GraphQL type's documentation follows.
//
// Informational statement that can be validated in the base layer blockchain
type getNoticeNotice struct {
	// Notice index within the context of the input that produced it
	Index int `json:"index"`
	// Notice data as a payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Proof object that allows this notice to be validated by the base layer blockchain
	Proof getNoticeNoticeProof `json:"proof"`
	// Input whose processing produced the notice
	Input getNoticeNoticeInput `json:"input"`
}

// GetIndex returns getNoticeNotice.Index, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetIndex() int { return v.Index }

// GetPayload returns getNoticeNotice.Payload, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetPayload() string { return v.Payload }

// GetProof returns getNoticeNotice.Proof, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetProof() getNoticeNoticeProof { return v.Proof }

// GetInput returns getNoticeNotice.Input, and is useful for accessing the field via an interface.
func (v *getNoticeNotice) GetInput() getNoticeNoticeInput { return v.Input }

// getNoticeNoticeInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getNoticeNoticeInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
}

// GetIndex returns getNoticeNoticeInput.Index, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeInput) GetIndex() int { return v.Index }

// getNoticeNoticeProof includes the requested fields of the GraphQL type Proof.
// The GraphQL type's documentation follows.
//
// Data that can be used as proof to validate notices and execute vouchers on the base layer blockchain
type getNoticeNoticeProof struct {
	// Validity proof for an output
	Validity getNoticeNoticeProofValidityOutputValidityProof `json:"validity"`
	// Data that allows the validity proof to be contextualized within submitted claims, given as a payload in Ethereum hex binary format, starting with '0x'
	Context string `json:"context"`
}

// GetValidity returns getNoticeNoticeProof.Validity, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProof) GetValidity() getNoticeNoticeProofValidityOutputValidityProof {
	return v.Validity
}

// GetContext returns getNoticeNoticeProof.Context, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProof) GetContext() string { return v.Context }

// getNoticeNoticeProofValidityOutputValidityProof includes the requested fields of the GraphQL type OutputValidityProof.
// The GraphQL type's documentation follows.
//
// Validity proof for an output
type getNoticeNoticeProofValidityOutputValidityProof struct {
	// Local input index within the context of the related epoch
	InputIndexWithinEpoch int `json:"inputIndexWithinEpoch"`
	// Output index within the context of the input that produced it
	OutputIndexWithinInput int `json:"outputIndexWithinInput"`
	// Merkle root of all output hashes of the related input, given in Ethereum hex binary format (32 bytes), starting with '0x'
	OutputHashesRootHash string `json:"outputHashesRootHash"`
	// Merkle root of all voucher hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	VouchersEpochRootHash string `json:"vouchersEpochRootHash"`
	// Merkle root of all notice hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	NoticesEpochRootHash string `json:"noticesEpochRootHash"`
	// Hash of the machine state claimed for the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	MachineStateHash string `json:"machineStateHash"`
	// Proof that this output hash is in the output-hashes merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashInOutputHashesSiblings []string `json:"outputHashInOutputHashesSiblings"`
	// Proof that this output-hashes root hash is in epoch's output merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashesInEpochSiblings []string `json:"outputHashesInEpochSiblings"`
}

// GetInputIndexWithinEpoch returns getNoticeNoticeProofValidityOutputValidityProof.InputIndexWithinEpoch, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetInputIndexWithinEpoch() int {
	return v.InputIndexWithinEpoch
}

// GetOutputIndexWithinInput returns getNoticeNoticeProofValidityOutputValidityProof.OutputIndexWithinInput, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputIndexWithinInput() int {
	return v.OutputIndexWithinInput
}

// GetOutputHashesRootHash returns getNoticeNoticeProofValidityOutputValidityProof.OutputHashesRootHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputHashesRootHash() string {
	return v.OutputHashesRootHash
}

// GetVouchersEpochRootHash returns getNoticeNoticeProofValidityOutputValidityProof.VouchersEpochRootHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetVouchersEpochRootHash() string {
	return v.VouchersEpochRootHash
}

// GetNoticesEpochRootHash returns getNoticeNoticeProofValidityOutputValidityProof.NoticesEpochRootHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetNoticesEpochRootHash() string {
	return v.NoticesEpochRootHash
}

// GetMachineStateHash returns getNoticeNoticeProofValidityOutputValidityProof.MachineStateHash, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetMachineStateHash() string {
	return v.MachineStateHash
}

// GetOutputHashInOutputHashesSiblings returns getNoticeNoticeProofValidityOutputValidityProof.OutputHashInOutputHashesSiblings, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputHashInOutputHashesSiblings() []string {
	return v.OutputHashInOutputHashesSiblings
}

// GetOutputHashesInEpochSiblings returns getNoticeNoticeProofValidityOutputValidityProof.OutputHashesInEpochSiblings, and is useful for accessing the field via an interface.
func (v *getNoticeNoticeProofValidityOutputValidityProof) GetOutputHashesInEpochSiblings() []string {
	return v.OutputHashesInEpochSiblings
}

// getNoticeResponse is returned by getNotice on success.
type getNoticeResponse struct {
	// Get a notice based on its index
	Notice getNoticeNotice `json:"notice"`
}

// GetNotice returns getNoticeResponse.Notice, and is useful for accessing the field via an interface.
func (v *getNoticeResponse) GetNotice() getNoticeNotice { return v.Notice }

// getNoticesNoticesNoticeConnection includes the requested fields of the GraphQL type NoticeConnection.
// The GraphQL type's documentation follows.
//
// Pagination result
type getNoticesNoticesNoticeConnection struct {
	// Pagination entries returned for the current page
	Edges []getNoticesNoticesNoticeConnectionEdgesNoticeEdge `json:"edges"`
}

// GetEdges returns getNoticesNoticesNoticeConnection.Edges, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnection) GetEdges() []getNoticesNoticesNoticeConnectionEdgesNoticeEdge {
	return v.Edges
}

// getNoticesNoticesNoticeConnectionEdgesNoticeEdge includes the requested fields of the GraphQL type NoticeEdge.
// The GraphQL type's documentation follows.
//
// Pagination entry
type getNoticesNoticesNoticeConnectionEdgesNoticeEdge struct {
	// Node instance
	Node getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice `json:"node"`
}

// GetNode returns getNoticesNoticesNoticeConnectionEdgesNoticeEdge.Node, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdge) GetNode() getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice {
	return v.Node
}

// getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice includes the requested fields of the GraphQL type Notice.
// The GraphQL type's documentation follows.
//
// Informational statement that can be validated in the base layer blockchain
type getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice struct {
	// Notice index within the context of the input that produced it
	Index int `json:"index"`
	// Notice data as a payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Proof object that allows this notice to be validated by the base layer blockchain
	Proof getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof `json:"proof"`
	// Input whose processing produced the notice
	Input getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeInput `json:"input"`
}

// GetIndex returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice.Index, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice) GetIndex() int { return v.Index }

// GetPayload returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice.Payload, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice) GetPayload() string {
	return v.Payload
}

// GetProof returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice.Proof, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice) GetProof() getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof {
	return v.Proof
}

// GetInput returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice.Input, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNotice) GetInput() getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeInput {
	return v.Input
}

// getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
}

// GetIndex returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeInput.Index, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeInput) GetIndex() int {
	return v.Index
}

// getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof includes the requested fields of the GraphQL type Proof.
// The GraphQL type's documentation follows.
//
// Data that can be used as proof to validate notices and execute vouchers on the base layer blockchain
type getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof struct {
	// Validity proof for an output
	Validity getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof `json:"validity"`
	// Data that allows the validity proof to be contextualized within submitted claims, given as a payload in Ethereum hex binary format, starting with '0x'
	Context string `json:"context"`
}

// GetValidity returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof.Validity, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof) GetValidity() getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof {
	return v.Validity
}

// GetContext returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof.Context, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProof) GetContext() string {
	return v.Context
}

// getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof includes the requested fields of the GraphQL type OutputValidityProof.
// The GraphQL type's documentation follows.
//
// Validity proof for an output
type getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof struct {
	// Local input index within the context of the related epoch
	InputIndexWithinEpoch int `json:"inputIndexWithinEpoch"`
	// Output index within the context of the input that produced it
	OutputIndexWithinInput int `json:"outputIndexWithinInput"`
	// Merkle root of all output hashes of the related input, given in Ethereum hex binary format (32 bytes), starting with '0x'
	OutputHashesRootHash string `json:"outputHashesRootHash"`
	// Merkle root of all voucher hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	VouchersEpochRootHash string `json:"vouchersEpochRootHash"`
	// Merkle root of all notice hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	NoticesEpochRootHash string `json:"noticesEpochRootHash"`
	// Hash of the machine state claimed for the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	MachineStateHash string `json:"machineStateHash"`
	// Proof that this output hash is in the output-hashes merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashInOutputHashesSiblings []string `json:"outputHashInOutputHashesSiblings"`
	// Proof that this output-hashes root hash is in epoch's output merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashesInEpochSiblings []string `json:"outputHashesInEpochSiblings"`
}

// GetInputIndexWithinEpoch returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.InputIndexWithinEpoch, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetInputIndexWithinEpoch() int {
	return v.InputIndexWithinEpoch
}

// GetOutputIndexWithinInput returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputIndexWithinInput, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputIndexWithinInput() int {
	return v.OutputIndexWithinInput
}

// GetOutputHashesRootHash returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputHashesRootHash, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputHashesRootHash() string {
	return v.OutputHashesRootHash
}

// GetVouchersEpochRootHash returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.VouchersEpochRootHash, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetVouchersEpochRootHash() string {
	return v.VouchersEpochRootHash
}

// GetNoticesEpochRootHash returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.NoticesEpochRootHash, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetNoticesEpochRootHash() string {
	return v.NoticesEpochRootHash
}

// GetMachineStateHash returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.MachineStateHash, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetMachineStateHash() string {
	return v.MachineStateHash
}

// GetOutputHashInOutputHashesSiblings returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputHashInOutputHashesSiblings, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputHashInOutputHashesSiblings() []string {
	return v.OutputHashInOutputHashesSiblings
}

// GetOutputHashesInEpochSiblings returns getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof.OutputHashesInEpochSiblings, and is useful for accessing the field via an interface.
func (v *getNoticesNoticesNoticeConnectionEdgesNoticeEdgeNodeNoticeProofValidityOutputValidityProof) GetOutputHashesInEpochSiblings() []string {
	return v.OutputHashesInEpochSiblings
}

// getNoticesResponse is returned by getNotices on success.
type getNoticesResponse struct {
	// Get notices with support for pagination
	Notices getNoticesNoticesNoticeConnection `json:"notices"`
}

// GetNotices returns getNoticesResponse.Notices, and is useful for accessing the field via an interface.
func (v *getNoticesResponse) GetNotices() getNoticesNoticesNoticeConnection { return v.Notices }

// getReportReport includes the requested fields of the GraphQL type Report.
// The GraphQL type's documentation follows.
//
// Application log or diagnostic information
type getReportReport struct {
	// Report index within the context of the input that produced it
	Index int `json:"index"`
	// Report data as a payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Input whose processing produced the report
	Input getReportReportInput `json:"input"`
}

// GetIndex returns getReportReport.Index, and is useful for accessing the field via an interface.
func (v *getReportReport) GetIndex() int { return v.Index }

// GetPayload returns getReportReport.Payload, and is useful for accessing the field via an interface.
func (v *getReportReport) GetPayload() string { return v.Payload }

// GetInput returns getReportReport.Input, and is useful for accessing the field via an interface.
func (v *getReportReport) GetInput() getReportReportInput { return v.Input }

// getReportReportInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getReportReportInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
}

// GetIndex returns getReportReportInput.Index, and is useful for accessing the field via an interface.
func (v *getReportReportInput) GetIndex() int { return v.Index }

// getReportResponse is returned by getReport on success.
type getReportResponse struct {
	// Get a report based on its index
	Report getReportReport `json:"report"`
}

// GetReport returns getReportResponse.Report, and is useful for accessing the field via an interface.
func (v *getReportResponse) GetReport() getReportReport { return v.Report }

// getVoucherResponse is returned by getVoucher on success.
type getVoucherResponse struct {
	// Get a voucher based on its index
	Voucher getVoucherVoucher `json:"voucher"`
}

// GetVoucher returns getVoucherResponse.Voucher, and is useful for accessing the field via an interface.
func (v *getVoucherResponse) GetVoucher() getVoucherVoucher { return v.Voucher }

// getVoucherVoucher includes the requested fields of the GraphQL type Voucher.
// The GraphQL type's documentation follows.
//
// Representation of a transaction that can be carried out on the base layer blockchain, such as a transfer of assets
type getVoucherVoucher struct {
	// Voucher index within the context of the input that produced it
	Index int `json:"index"`
	// Transaction payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Transaction destination address in Ethereum hex binary format (20 bytes), starting with '0x'
	Destination string `json:"destination"`
	// Proof object that allows this voucher to be validated and executed on the base layer blockchain
	Proof getVoucherVoucherProof `json:"proof"`
	// Input whose processing produced the voucher
	Input getVoucherVoucherInput `json:"input"`
}

// GetIndex returns getVoucherVoucher.Index, and is useful for accessing the field via an interface.
func (v *getVoucherVoucher) GetIndex() int { return v.Index }

// GetPayload returns getVoucherVoucher.Payload, and is useful for accessing the field via an interface.
func (v *getVoucherVoucher) GetPayload() string { return v.Payload }

// GetDestination returns getVoucherVoucher.Destination, and is useful for accessing the field via an interface.
func (v *getVoucherVoucher) GetDestination() string { return v.Destination }

// GetProof returns getVoucherVoucher.Proof, and is useful for accessing the field via an interface.
func (v *getVoucherVoucher) GetProof() getVoucherVoucherProof { return v.Proof }

// GetInput returns getVoucherVoucher.Input, and is useful for accessing the field via an interface.
func (v *getVoucherVoucher) GetInput() getVoucherVoucherInput { return v.Input }

// getVoucherVoucherInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getVoucherVoucherInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
}

// GetIndex returns getVoucherVoucherInput.Index, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherInput) GetIndex() int { return v.Index }

// getVoucherVoucherProof includes the requested fields of the GraphQL type Proof.
// The GraphQL type's documentation follows.
//
// Data that can be used as proof to validate notices and execute vouchers on the base layer blockchain
type getVoucherVoucherProof struct {
	// Validity proof for an output
	Validity getVoucherVoucherProofValidityOutputValidityProof `json:"validity"`
	// Data that allows the validity proof to be contextualized within submitted claims, given as a payload in Ethereum hex binary format, starting with '0x'
	Context string `json:"context"`
}

// GetValidity returns getVoucherVoucherProof.Validity, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProof) GetValidity() getVoucherVoucherProofValidityOutputValidityProof {
	return v.Validity
}

// GetContext returns getVoucherVoucherProof.Context, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProof) GetContext() string { return v.Context }

// getVoucherVoucherProofValidityOutputValidityProof includes the requested fields of the GraphQL type OutputValidityProof.
// The GraphQL type's documentation follows.
//
// Validity proof for an output
type getVoucherVoucherProofValidityOutputValidityProof struct {
	// Local input index within the context of the related epoch
	InputIndexWithinEpoch int `json:"inputIndexWithinEpoch"`
	// Output index within the context of the input that produced it
	OutputIndexWithinInput int `json:"outputIndexWithinInput"`
	// Merkle root of all output hashes of the related input, given in Ethereum hex binary format (32 bytes), starting with '0x'
	OutputHashesRootHash string `json:"outputHashesRootHash"`
	// Merkle root of all voucher hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	VouchersEpochRootHash string `json:"vouchersEpochRootHash"`
	// Merkle root of all notice hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	NoticesEpochRootHash string `json:"noticesEpochRootHash"`
	// Hash of the machine state claimed for the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	MachineStateHash string `json:"machineStateHash"`
	// Proof that this output hash is in the output-hashes merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashInOutputHashesSiblings []string `json:"outputHashInOutputHashesSiblings"`
	// Proof that this output-hashes root hash is in epoch's output merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashesInEpochSiblings []string `json:"outputHashesInEpochSiblings"`
}

// GetInputIndexWithinEpoch returns getVoucherVoucherProofValidityOutputValidityProof.InputIndexWithinEpoch, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetInputIndexWithinEpoch() int {
	return v.InputIndexWithinEpoch
}

// GetOutputIndexWithinInput returns getVoucherVoucherProofValidityOutputValidityProof.OutputIndexWithinInput, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetOutputIndexWithinInput() int {
	return v.OutputIndexWithinInput
}

// GetOutputHashesRootHash returns getVoucherVoucherProofValidityOutputValidityProof.OutputHashesRootHash, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetOutputHashesRootHash() string {
	return v.OutputHashesRootHash
}

// GetVouchersEpochRootHash returns getVoucherVoucherProofValidityOutputValidityProof.VouchersEpochRootHash, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetVouchersEpochRootHash() string {
	return v.VouchersEpochRootHash
}

// GetNoticesEpochRootHash returns getVoucherVoucherProofValidityOutputValidityProof.NoticesEpochRootHash, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetNoticesEpochRootHash() string {
	return v.NoticesEpochRootHash
}

// GetMachineStateHash returns getVoucherVoucherProofValidityOutputValidityProof.MachineStateHash, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetMachineStateHash() string {
	return v.MachineStateHash
}

// GetOutputHashInOutputHashesSiblings returns getVoucherVoucherProofValidityOutputValidityProof.OutputHashInOutputHashesSiblings, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetOutputHashInOutputHashesSiblings() []string {
	return v.OutputHashInOutputHashesSiblings
}

// GetOutputHashesInEpochSiblings returns getVoucherVoucherProofValidityOutputValidityProof.OutputHashesInEpochSiblings, and is useful for accessing the field via an interface.
func (v *getVoucherVoucherProofValidityOutputValidityProof) GetOutputHashesInEpochSiblings() []string {
	return v.OutputHashesInEpochSiblings
}

// getVouchersResponse is returned by getVouchers on success.
type getVouchersResponse struct {
	// Get vouchers with support for pagination
	Vouchers getVouchersVouchersVoucherConnection `json:"vouchers"`
}

// GetVouchers returns getVouchersResponse.Vouchers, and is useful for accessing the field via an interface.
func (v *getVouchersResponse) GetVouchers() getVouchersVouchersVoucherConnection { return v.Vouchers }

// getVouchersVouchersVoucherConnection includes the requested fields of the GraphQL type VoucherConnection.
// The GraphQL type's documentation follows.
//
// Pagination result
type getVouchersVouchersVoucherConnection struct {
	// Pagination entries returned for the current page
	Edges []getVouchersVouchersVoucherConnectionEdgesVoucherEdge `json:"edges"`
}

// GetEdges returns getVouchersVouchersVoucherConnection.Edges, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnection) GetEdges() []getVouchersVouchersVoucherConnectionEdgesVoucherEdge {
	return v.Edges
}

// getVouchersVouchersVoucherConnectionEdgesVoucherEdge includes the requested fields of the GraphQL type VoucherEdge.
// The GraphQL type's documentation follows.
//
// Pagination entry
type getVouchersVouchersVoucherConnectionEdgesVoucherEdge struct {
	// Node instance
	Node getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher `json:"node"`
}

// GetNode returns getVouchersVouchersVoucherConnectionEdgesVoucherEdge.Node, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdge) GetNode() getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher {
	return v.Node
}

// getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher includes the requested fields of the GraphQL type Voucher.
// The GraphQL type's documentation follows.
//
// Representation of a transaction that can be carried out on the base layer blockchain, such as a transfer of assets
type getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher struct {
	// Voucher index within the context of the input that produced it
	Index int `json:"index"`
	// Transaction payload in Ethereum hex binary format, starting with '0x'
	Payload string `json:"payload"`
	// Transaction destination address in Ethereum hex binary format (20 bytes), starting with '0x'
	Destination string `json:"destination"`
	// Proof object that allows this voucher to be validated and executed on the base layer blockchain
	Proof getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof `json:"proof"`
	// Input whose processing produced the voucher
	Input getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherInput `json:"input"`
}

// GetIndex returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Index, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetIndex() int {
	return v.Index
}

// GetPayload returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Payload, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetPayload() string {
	return v.Payload
}

// GetDestination returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Destination, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetDestination() string {
	return v.Destination
}

// GetProof returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Proof, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetProof() getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof {
	return v.Proof
}

// GetInput returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher.Input, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucher) GetInput() getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherInput {
	return v.Input
}

// getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherInput includes the requested fields of the GraphQL type Input.
// The GraphQL type's documentation follows.
//
// Request submitted to the application to advance its state
type getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherInput struct {
	// Input index starting from genesis
	Index int `json:"index"`
}

// GetIndex returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherInput.Index, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherInput) GetIndex() int {
	return v.Index
}

// getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof includes the requested fields of the GraphQL type Proof.
// The GraphQL type's documentation follows.
//
// Data that can be used as proof to validate notices and execute vouchers on the base layer blockchain
type getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof struct {
	// Validity proof for an output
	Validity getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof `json:"validity"`
	// Data that allows the validity proof to be contextualized within submitted claims, given as a payload in Ethereum hex binary format, starting with '0x'
	Context string `json:"context"`
}

// GetValidity returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof.Validity, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof) GetValidity() getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof {
	return v.Validity
}

// GetContext returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof.Context, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProof) GetContext() string {
	return v.Context
}

// getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof includes the requested fields of the GraphQL type OutputValidityProof.
// The GraphQL type's documentation follows.
//
// Validity proof for an output
type getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof struct {
	// Local input index within the context of the related epoch
	InputIndexWithinEpoch int `json:"inputIndexWithinEpoch"`
	// Output index within the context of the input that produced it
	OutputIndexWithinInput int `json:"outputIndexWithinInput"`
	// Merkle root of all output hashes of the related input, given in Ethereum hex binary format (32 bytes), starting with '0x'
	OutputHashesRootHash string `json:"outputHashesRootHash"`
	// Merkle root of all voucher hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	VouchersEpochRootHash string `json:"vouchersEpochRootHash"`
	// Merkle root of all notice hashes of the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	NoticesEpochRootHash string `json:"noticesEpochRootHash"`
	// Hash of the machine state claimed for the related epoch, given in Ethereum hex binary format (32 bytes), starting with '0x'
	MachineStateHash string `json:"machineStateHash"`
	// Proof that this output hash is in the output-hashes merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashInOutputHashesSiblings []string `json:"outputHashInOutputHashesSiblings"`
	// Proof that this output-hashes root hash is in epoch's output merkle tree. This array of siblings is bottom-up ordered (from the leaf to the root). Each hash is given in Ethereum hex binary format (32 bytes), starting with '0x'.
	OutputHashesInEpochSiblings []string `json:"outputHashesInEpochSiblings"`
}

// GetInputIndexWithinEpoch returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.InputIndexWithinEpoch, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetInputIndexWithinEpoch() int {
	return v.InputIndexWithinEpoch
}

// GetOutputIndexWithinInput returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputIndexWithinInput, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputIndexWithinInput() int {
	return v.OutputIndexWithinInput
}

// GetOutputHashesRootHash returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputHashesRootHash, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputHashesRootHash() string {
	return v.OutputHashesRootHash
}

// GetVouchersEpochRootHash returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.VouchersEpochRootHash, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetVouchersEpochRootHash() string {
	return v.VouchersEpochRootHash
}

// GetNoticesEpochRootHash returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.NoticesEpochRootHash, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetNoticesEpochRootHash() string {
	return v.NoticesEpochRootHash
}

// GetMachineStateHash returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.MachineStateHash, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetMachineStateHash() string {
	return v.MachineStateHash
}

// GetOutputHashInOutputHashesSiblings returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputHashInOutputHashesSiblings, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputHashInOutputHashesSiblings() []string {
	return v.OutputHashInOutputHashesSiblings
}

// GetOutputHashesInEpochSiblings returns getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof.OutputHashesInEpochSiblings, and is useful for accessing the field via an interface.
func (v *getVouchersVouchersVoucherConnectionEdgesVoucherEdgeNodeVoucherProofValidityOutputValidityProof) GetOutputHashesInEpochSiblings() []string {
	return v.OutputHashesInEpochSiblings
}

// The query or mutation executed by getInput.
const getInput_Operation = `
query getInput ($index: Int!) {
	input(index: $index) {
		index
		status
		msgSender
		timestamp
		blockNumber
		payload
	}
}
`

func getInput(
	ctx context.Context,
	client graphql.Client,
	index int,
) (*getInputResponse, error) {
	req := &graphql.Request{
		OpName: "getInput",
		Query:  getInput_Operation,
		Variables: &__getInputInput{
			Index: index,
		},
	}
	var err error

	var data getInputResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getInputNotices.
const getInputNotices_Operation = `
query getInputNotices ($inputIndex: Int!) {
	input(index: $inputIndex) {
		index
		notices {
			edges {
				node {
					index
					payload
					proof {
						validity {
							inputIndexWithinEpoch
							outputIndexWithinInput
							outputHashesRootHash
							vouchersEpochRootHash
							noticesEpochRootHash
							machineStateHash
							outputHashInOutputHashesSiblings
							outputHashesInEpochSiblings
						}
						context
					}
				}
			}
		}
	}
}
`

func getInputNotices(
	ctx context.Context,
	client graphql.Client,
	inputIndex int,
) (*getInputNoticesResponse, error) {
	req := &graphql.Request{
		OpName: "getInputNotices",
		Query:  getInputNotices_Operation,
		Variables: &__getInputNoticesInput{
			InputIndex: inputIndex,
		},
	}
	var err error

	var data getInputNoticesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getInputVouchers.
const getInputVouchers_Operation = `
query getInputVouchers ($inputIndex: Int!) {
	input(index: $inputIndex) {
		index
		vouchers {
			edges {
				node {
					index
					payload
					destination
					proof {
						validity {
							inputIndexWithinEpoch
							outputIndexWithinInput
							outputHashesRootHash
							vouchersEpochRootHash
							noticesEpochRootHash
							machineStateHash
							outputHashInOutputHashesSiblings
							outputHashesInEpochSiblings
						}
						context
					}
				}
			}
		}
	}
}
`

func getInputVouchers(
	ctx context.Context,
	client graphql.Client,
	inputIndex int,
) (*getInputVouchersResponse, error) {
	req := &graphql.Request{
		OpName: "getInputVouchers",
		Query:  getInputVouchers_Operation,
		Variables: &__getInputVouchersInput{
			InputIndex: inputIndex,
		},
	}
	var err error

	var data getInputVouchersResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getInputs.
const getInputs_Operation = `
query getInputs {
	inputs {
		edges {
			node {
				index
				status
				msgSender
				timestamp
				blockNumber
				payload
			}
		}
	}
}
`

func getInputs(
	ctx context.Context,
	client graphql.Client,
) (*getInputsResponse, error) {
	req := &graphql.Request{
		OpName: "getInputs",
		Query:  getInputs_Operation,
	}
	var err error

	var data getInputsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getNotice.
const getNotice_Operation = `
query getNotice ($noticeIndex: Int!, $inputIndex: Int!) {
	notice(noticeIndex: $noticeIndex, inputIndex: $inputIndex) {
		index
		payload
		proof {
			validity {
				inputIndexWithinEpoch
				outputIndexWithinInput
				outputHashesRootHash
				vouchersEpochRootHash
				noticesEpochRootHash
				machineStateHash
				outputHashInOutputHashesSiblings
				outputHashesInEpochSiblings
			}
			context
		}
		input {
			index
		}
	}
}
`

func getNotice(
	ctx context.Context,
	client graphql.Client,
	noticeIndex int,
	inputIndex int,
) (*getNoticeResponse, error) {
	req := &graphql.Request{
		OpName: "getNotice",
		Query:  getNotice_Operation,
		Variables: &__getNoticeInput{
			NoticeIndex: noticeIndex,
			InputIndex:  inputIndex,
		},
	}
	var err error

	var data getNoticeResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getNotices.
const getNotices_Operation = `
query getNotices {
	notices {
		edges {
			node {
				index
				payload
				proof {
					validity {
						inputIndexWithinEpoch
						outputIndexWithinInput
						outputHashesRootHash
						vouchersEpochRootHash
						noticesEpochRootHash
						machineStateHash
						outputHashInOutputHashesSiblings
						outputHashesInEpochSiblings
					}
					context
				}
				input {
					index
				}
			}
		}
	}
}
`

func getNotices(
	ctx context.Context,
	client graphql.Client,
) (*getNoticesResponse, error) {
	req := &graphql.Request{
		OpName: "getNotices",
		Query:  getNotices_Operation,
	}
	var err error

	var data getNoticesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getReport.
const getReport_Operation = `
query getReport ($reportIndex: Int!, $inputIndex: Int!) {
	report(reportIndex: $reportIndex, inputIndex: $inputIndex) {
		index
		payload
		input {
			index
		}
	}
}
`

func getReport(
	ctx context.Context,
	client graphql.Client,
	reportIndex int,
	inputIndex int,
) (*getReportResponse, error) {
	req := &graphql.Request{
		OpName: "getReport",
		Query:  getReport_Operation,
		Variables: &__getReportInput{
			ReportIndex: reportIndex,
			InputIndex:  inputIndex,
		},
	}
	var err error

	var data getReportResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getVoucher.
const getVoucher_Operation = `
query getVoucher ($voucherIndex: Int!, $inputIndex: Int!) {
	voucher(voucherIndex: $voucherIndex, inputIndex: $inputIndex) {
		index
		payload
		destination
		proof {
			validity {
				inputIndexWithinEpoch
				outputIndexWithinInput
				outputHashesRootHash
				vouchersEpochRootHash
				noticesEpochRootHash
				machineStateHash
				outputHashInOutputHashesSiblings
				outputHashesInEpochSiblings
			}
			context
		}
		input {
			index
		}
	}
}
`

func getVoucher(
	ctx context.Context,
	client graphql.Client,
	voucherIndex int,
	inputIndex int,
) (*getVoucherResponse, error) {
	req := &graphql.Request{
		OpName: "getVoucher",
		Query:  getVoucher_Operation,
		Variables: &__getVoucherInput{
			VoucherIndex: voucherIndex,
			InputIndex:   inputIndex,
		},
	}
	var err error

	var data getVoucherResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getVouchers.
const getVouchers_Operation = `
query getVouchers {
	vouchers {
		edges {
			node {
				index
				payload
				destination
				proof {
					validity {
						inputIndexWithinEpoch
						outputIndexWithinInput
						outputHashesRootHash
						vouchersEpochRootHash
						noticesEpochRootHash
						machineStateHash
						outputHashInOutputHashesSiblings
						outputHashesInEpochSiblings
					}
					context
				}
				input {
					index
				}
			}
		}
	}
}
`

func getVouchers(
	ctx context.Context,
	client graphql.Client,
) (*getVouchersResponse, error) {
	req := &graphql.Request{
		OpName: "getVouchers",
		Query:  getVouchers_Operation,
	}
	var err error

	var data getVouchersResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
