# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-22.04
    steps:
      - uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGELOG.md
