name: Check Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-22.04

    steps:
      - uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md

          