# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Clean-up Docker images

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  cleanup:
    name: Cleanup ghcr.io/cartesi/${{ matrix.image }} CI images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        image:
          - rollups-node
          - rollups-node-devnet
    steps:
      # Remove PR-scoped tags immediately.
      - name: Prune PR tags
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          organization: cartesi
          container: ${{ matrix.image }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prune-untagged: false
          keep-last: 0
          prune-tags-regexes: |
            ^pr-${{ github.event.number }}$

      # Prune stale CI images older than 7 days to avoid deleting
      # images needed by concurrently running workflows.
      - name: Prune stale CI tags
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          organization: cartesi
          container: ${{ matrix.image }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prune-untagged: false
          keep-last: 0
          older-than: 7 days
          prune-tags-regexes: |
            ^ci-
