name: Assess Go code quality

on:
  push:
    paths:
      - ".github/workflows/go-code-quality.yml"
      - ".golangci.yml"
      - "cmd/**"
      - "internal/**"

jobs:
  assess-go-code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
